### ISSUE TITLE
Authentication bug: no signing credentials found but AWS CLI works

### ISSUE THREAD

**Issue by ps-spark** [awslabs/mountpoint-s3#1008]
### Mountpoint for Amazon S3 version

1.8.0

### AWS Region

eu-central-1

### Describe the running environment

Running on an Amazon Linux (RedHat) inside a Docker container.

### Mountpoint options

```shell
mount-s3 bucket-raw-340752333339 /mnt/my-bucket --profile jbdata-admin
```

### What happened?

Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket scene-intel-rosbag-ingestion-raw-340752333339 in region eu-central-1
    1: Client error
    2: No signing credentials found

### Relevant log output

```shell
Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket scene-intel-rosbag-ingestion-raw-340752333339 in region eu-central-1
    1: Client error
    2: No signing credentials found
```

**Comment by ps-spark** [comment]
Hi Guys,

I'm experiencing auth problem running mount-s3 in a Docker container (AWS EMR image). The AWS profiles are configured in the ~/.aws folder using SSO auth. AWS CLI is working.

**version**: 1.8.0

```
mount-s3 bucket-raw-340752333339 /mnt/my-bucket --profile jbdata-admin --profile jbdata-admin
Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket scene-intel-rosbag-ingestion-raw-340752333339 in region eu-central-1
    1: Client error
    2: No signing credentials found
Error: Failed to create mount process
```

AWS CLI
```
aws s3 ls --profile jbdata-admin
2024-09-11 06:12:47 addf-demo-bucket-fd97bda4-8abb746dd2b06be274a04b443
2024-09-11 06:12:43 addf-demo-xxx-fd97bda4-8abb746dd2b06be274a04b443e1

```

Any idea? Is it related to SSO?

**Comment by ps-spark** [comment]
I have just tested it on an Ubuntu without container, the problem is the same.

**Comment by jagad89** [comment]
I am trying to configure with environment variable, by adding variables in ~/.profile

```
AWS_ACCESS_KEY_ID=XXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXX
AWS_REGION=us-east-X
```

> Error: Failed to create S3 client
> 
> Caused by:
>     0: initial ListObjectsV2 failed for bucket my_bucket_name in region us-east-X
>     1: Client error
>     2: No signing credentials found
> Error: Failed to create mount process

I am using `mount-s3 1.8.0`

**Comment by dannycjones** [comment]
Hey both!

>Any idea? Is it related to SSO?

SSO isn't supported in Mountpoint today, we have a feature request open for it. Please do react 👍 to the main post so we can measure interest there! https://github.com/awslabs/mountpoint-s3/issues/433

If you're not using SSO, reviewing Mountpoint logs would be the best next step and including `--debug-crt` to see logs related to the auth stack. https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md

**Comment by dannycjones** [comment]
@jagad89 are you working together with @ps-spark? If not, I'd recommend opening a new issue so we can track each issue independently. https://github.com/awslabs/mountpoint-s3/issues/new/choose

**Comment by ps-spark** [comment]
Hi @dannycjones,

No, we are not working together and @jagad89 is obviously not using SSO, so he's got another problem.

**Comment by ps-spark** [comment]
> Hey both!
> 
> > Any idea? Is it related to SSO?
> 
> SSO isn't supported in Mountpoint today, we have a feature request open for it. Please do react 👍 to the main post so we can measure interest there! #433
> 
> If you're not using SSO, reviewing Mountpoint logs would be the best next step and including `--debug-crt` to see logs related to the auth stack. https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md

Sorry, I missed that somehow.

**Comment by dannycjones** [comment]
I'll close this for now, since we have #433 tracking SSO support.
