### ISSUE TITLE
Build.rs for crt-sys crate fails on windows with conflicting math.inl implementations and other errors

### ISSUE THREAD

**Issue by NukaCody** [awslabs/mountpoint-s3#1056]
### Mountpoint for Amazon S3 version

main branch

### AWS Region

us-east-1

### Describe the running environment

Windows 11

### Mountpoint options

```shell
None
```

### What happened?

Trying to leverage crt-sys crate on windows, potentially as a future PR for windows support

**Comment by NukaCody** [comment]
## Things I've tried

When building on windows as is, the aws-c-common runtime provides multiple definitions for math.h (inside of [math.inl](https://github.com/awslabs/aws-c-common/blob/69789467ebb76526bffc8ad0e552858256b6a326/include/aws/common/math.inl#L18)). Clang will get multiple definitions of aws_ctz_* and aws_clz_* types from both the `math.gcc_builtin.inl` and `math.msvc.inl` and cause a redefinition failure. I'm not sure how `math.msvc.inl` is being included as I'm building as is on windows without any additional clang arguements/macro definitions. Trying both blocklist_file and blocklist_item did not work for me (I believe Clang MUST go through all header definitions). Manually modifying the `math.inl` file to include `math.msvc.inl` only by force fixes the redefinition conflict but causes Bindgen to panic (unsure why). Manually modifying `math.inl` to force the pure C implementation `aws/common/math.fallback.inl` will pass by clang and build.rs finishes. However, for some unknown reason, [logging_shim.rs](https://github.com/awslabs/mountpoint-s3/blob/0415b5c9e9e0be906ce17446834f2aadc2655b79/mountpoint-s3-crt-sys/src/logging_shim.rs#L7) and lib.rs will fail to compile as it's not picking up the generated types.

**Comment by unexge** [comment]
Hey @NukaCody, we don't support Windows at the moment. We may accept small PRs to fix Windows build as long as they don't break anything on Linux, but we can't guarantee anything. Your particular issue seems related to CRT, I'd suggest reaching out to them for any queries.
