### ISSUE TITLE
mountpoint-s3-csi-driver for EKS to support Dynamic Provisioning

### ISSUE THREAD

**Issue by prabaksa** [awslabs/mountpoint-s3#1119]
### Tell us more about this new feature.

mountpoint-s3-csi-driver for EKS only supports static provisioning as of today and we have a requirement where we need Dynamic Provisioning.

**Comment by dannycjones** [comment]
Hey @prabaksa, thank you for your interest!

We have tracking issue https://github.com/awslabs/mountpoint-s3-csi-driver/issues/125 over on the Mountpoint CSI Driver repository, please do go ahead and react with a thumbs up (👍) to the main issue body. The issue reactions are how we are tracking interest in the feature.

I'll resolve this one as a duplicate.
