### ISSUE TITLE
Test effects of concurrent mutations on directory structure

### ISSUE THREAD

**Issue by jamesbornholt** [awslabs/mountpoint-s3#128]
Right now we don't have any test coverage of concurrent mutation—what happens if objects are created/mutated/deleted on the S3 side while Mountpoint is interacting with them. We need to get test coverage of these behaviors and then define our intended semantics for them.

- [x] Concurrent object mutation while reading -- cause future reads to fail when detected
- [ ] Concurrent creation/removal of implicit directories -- create/remove `foo/bar` when `foo` already existed
- [ ] Concurrent creation of explicit directories -- create/remove `foo/` when `foo` already existed

**Comment by sauraank** [comment]
I think fuse test for prefetching covers the case of causing failure to future reads when concurrent mutation are done while reading? Or we talking about something else here?
