### ISSUE TITLE
Make it available for any S3 compatible back-end storage 

### ISSUE THREAD

**Issue by debnsuma** [awslabs/mountpoint-s3#146]
### Tell us more about this new feature.

This is a fantastic project, it would be nice if we can have it compatible with any S3 compatible storage in future.

**Comment by virtualirfan** [comment]
Looks like a duplicate of #144

**Comment by debnsuma** [comment]
Yes, i just realized it after creating this request.

**Comment by jamesbornholt** [comment]
Thanks! Going to close this in favor of #144, which has some pointers on compatibility.
