### ISSUE TITLE
Add option --profile for a specific profile in the AWS credentials file

### ISSUE THREAD

**Issue by bingzhang00** [awslabs/mountpoint-s3#151]
### Tell us more about this new feature.

It would be nice if we can have an option `--profile`, like in other AWS command-line tools, so that we can choose a specific profile to use from ~/.aws/credentials.  Right now it seems the only way to select a different profile is via environment variables, which is also not documented. 

Current behavior

```
./target/release/mount-s3 --profile
error: Found argument '--profile' which wasn't expected, or isn't valid in this context

        If you tried to supply `--profile` as a value rather than a flag, use `-- --profile`
```

**Comment by jamesbornholt** [comment]
Thanks! We'll definitely add this. In the meantime, I'll update the documentation so at least it's clear that you can use the `AWS_PROFILE` environment variable to select a profile.

**Comment by ooboyle-rs10** [comment]
Latest version has --profile and work well for me. Thank you.
