### ISSUE TITLE
Mounted filesystem is read-only

### ISSUE THREAD

**Issue by jht-prog** [awslabs/mountpoint-s3#153]
### Mountpoint for Amazon S3 version

mountpoint-s3 0.2.0-b8363a4

### AWS Region

us-east-1

### Describe the running environment

Running Ubuntu 20.04 on the headnode of a pcluster with fullaccesss3 privileges.

### What happened?

Was able to build client and mount s3 bucket but the file system is write only, reads contents just fine. Probably doing something simple wrong. Using file-mode doesn't seem to fix it.

**Comment by dannycjones** [comment]
Thanks for trying out the project!

Mountpoint is currently an alpha release, and does not yet support read-write access. We are already working on sequential write access to files, tracked in #27. We have also shared a number of other features we hope to add in the [Mountpoint for Amazon S3 public roadmap](https://github.com/orgs/awslabs/projects/84).

**Comment by jht-prog** [comment]
Thanks for the quick feedback!

Hoot
