### ISSUE TITLE
Local-only temporary write mode

### ISSUE THREAD

**Issue by drwelby** [awslabs/mountpoint-s3#163]
### Tell us more about this new feature.

Some software will write temporary files in the same location as the data source it is reading. Typically these are index files or caches to speed up subsequent access. Since these files are temporary and may be specific to the reader's operation they do not need to be persisted back to the data store. So this "local write" mode would allow writing to the mount point, but the files would only exist locally. 

This could be confusing and anti-pattern enough to be a horrible idea, with the ideal solution to fix the readers to work with the idea of read-only file systems and always write temporary files to a local location. However for legacy or closed code this could be useful.

**Comment by jamesbornholt** [comment]
Super interesting idea. It would definitely have to be opt-in, with some loud warnings that "files will never be persisted", but I can see how it would be useful. We'll look into this one.

**Comment by nodakai** [comment]
Might be possible with `overlayfs` or `aufs`? Haven't tried them myself, though.

**Comment by gpicciani** [comment]
We have looked into this one and we have decided to not prioritize this feature this year, according to Mountpoint’s core mission and tenets.

**Comment by gpicciani** [comment]
Mapping these requirements to Mountpoint’s core mission and tenets led us to not prioritize this feature this year
