### ISSUE TITLE
Run on Ubuntu Server or Debian based Linux

### ISSUE THREAD

**Issue by crypto-br** [awslabs/mountpoint-s3#165]
### Tell us more about this new feature.

To run on Ubuntu Server or Debian based Linux, just use:

**sudo apt install fuse libfuse-dev cmake clang pkg-config**

other steps are the same

TKS

**Comment by dheera** [comment]
It would be really nice if there were a .deb package for this!

**Comment by jamesbornholt** [comment]
@dheera agreed! We're looking into our preferred distribution mechanism(s) right now. We'll update this issue when we have more to share there.
