### ISSUE TITLE
Usage in Kubernetes?

### ISSUE THREAD

**Issue by vsoch** [awslabs/mountpoint-s3#180]
Hi!  Has anyone tried this in the context of Kubernetes? I could create a daemon set to install the needed deps for the nodes, and the main thing I think I'm not sure how to do is to ensure there are credentials there for doing the bind. Has anyone tried this / has experience and could make some suggestions? Thank you!

**Comment by pr0ton11** [comment]
Hi. I am currently in the process of trying to write a CSI based on this: https://github.com/pr0ton11/csi-mountpoint-s3.
It's not the fastest going project (because I have limited time), but eventually it should allow you to use mountpoint-s3 within Kubernetes.

For the credentials, I think you need to mount a secretMap into the container that runs mountpoint-s3.

**Comment by vsoch** [comment]
I would be happy to test if/when you have something. I know it's not the fastest, but do you have an estimate - are we talking on the order of weeks / months/ next year?

**Comment by pr0ton11** [comment]
I would say months probably. But it should have something usable in the next coming months

**Comment by vsoch** [comment]
okay great! Do you want me to watch this issue for updates, or the repository itself? I'm happy to test / give feedback if/when you need.

**Comment by pr0ton11** [comment]
I will update this comment

**Comment by pr0ton11** [comment]
Unfortunately I ran into a lot of issues while testing mountpoint-s3 and it's not really ready yet to be implemented into a CSI: A lot of admin code is necessary for the provisioner and it seems like mountpoint-s3 doesn't want to support my use case (non-AWS buckets).
I hope they will be more open in the future but for now the project is frozen.
Lets hope they will provide a CSI at some point

**Comment by vsoch** [comment]
okay no worries - thanks for trying this out @pr0ton11 ! I'll keep following the issue in case this changes in the future. 

If you are needing one, I've found the one that worked easiest for me (and the only one thus far) is their oidc provider: https://flux-framework.org/flux-operator/deployment/aws.html#prepare-the-oidc-provider-for-eks (that's my docs for the project I worked on, it should be linked there).

**Comment by dannycjones** [comment]
>it seems like mountpoint-s3 doesn't want to support my use case (non-AWS buckets).

While we're not supporting S3-like services, we would like to welcome minor compatibility fixes or performance improvements for them so long as the changes can be tested with Amazon S3.

**Comment by dannycjones** [comment]
FYI for those following this issue: we do have a similar issue open for Kubernetes support via a CSI driver (#150), but we have no new information to share there right now.

**Comment by jamesbornholt** [comment]
I'm going to close this in favor of #150, which is where we're tracking support for a CSI driver for Mountpoint. Thanks!
