### ISSUE TITLE
Add support for unsigned requests

### ISSUE THREAD

**Issue by pschmied** [awslabs/mountpoint-s3#181]
### Tell us more about this new feature.

Allowing for unsigned requests would allow Mountpoint to work as a client for public, world-readable S3 buckets. This would function similarly to the AWS CLI's `--no-sign-request` flag (e.g. https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/ls.html).

**Comment by jamesbornholt** [comment]
Done in #209.
