### ISSUE TITLE
Support for rmdir

### ISSUE THREAD

**Issue by dannycjones** [awslabs/mountpoint-s3#194]
Creating this issue independent of #78.

- [x] https://github.com/awslabs/mountpoint-s3/issues/83
- [ ] Implement rmdir in the filesystem

**Comment by dannycjones** [comment]
Creating a directory is a local-only concept for Mountpoint. However, directory markers may exist from other applications such as S3A or the AWS Console.

Open question: should _rmdir_ remove those?

**Comment by jamesbornholt** [comment]
My guess is no? It creates a weird situation where `rmdir foo` works if your keyspace looks like:
```
foo/
```
but not if it looks like
```
foo/a.txt
```
or even
```
foo/
foo/a.txt
```

**Comment by dannycjones** [comment]
I'd argue that `rmdir` would work in both cases. In the former, we delete the marker. In the latter, we perform the delete and it succeeds anyway.

There's some risk around `rmdir` where the keyspace looks like this, since you could remove a number of parent directories also:

```
foo/bar/baz/
```

If we stick to _never deleting directory markers_, then what do we expect from `rmdir`?

1. `rmdir` is a no-op, and the directory will still exist locally and remotely
2. `rmdir` is local-only, and the directory will be dropped from the superblock. A subsequent lookup on the parent may reintroduce the directory.
3. Something else?

**Comment by sauraank** [comment]
> My guess is no? It creates a weird situation where `rmdir foo` works if your keyspace looks like:
> 
> ```
> foo/
> ```
> 
> but not if it looks like
> 
> ```
> foo/a.txt
> ```
> 
> or even
> 
> ```
> foo/
> foo/a.txt
> ```

rmdir is for removing empty directory right?
