### ISSUE TITLE
mount-s3: command not found

### ISSUE THREAD

**Issue by karthikraju523** [awslabs/mountpoint-s3#195]
### Mountpoint for Amazon S3 version

mountpoint

### AWS Region

us-east-1

### Describe the running environment

Amazon Ec2 

### What happened?

Hi 
While compiling mountpoint-s3, fuser 6 warning prompting. path - /root/mountpoint-s3
target/release/mounts-s3 binary files extracted in mountpoint-s3.

Still :-  mount-s3: command not found.

Command used - mount-s3 bucket_Name /root/mnt

### Relevant log output

```shell
warning: `fuser` (lib) generated 6 warnings
   Compiling tracing-subscriber v0.3.16
   Compiling ctrlc v3.2.5
   Compiling async-channel v1.8.0
   Compiling hdrhistogram v7.5.2
   Compiling const_format v0.2.30
   Compiling async-lock v2.6.0
   Compiling bytes v1.4.0
   Compiling home v0.5.4
   Compiling mountpoint-s3-crt v0.2.0 (/root/mountpoint-s3/mountpoint-s3-crt)
   Compiling mountpoint-s3-client v0.2.0 (/root/mountpoint-s3/mountpoint-s3-client)
   Compiling git2 v0.16.1
   Compiling built v0.6.0
   Compiling mountpoint-s3 v0.2.0 (/root/mountpoint-s3/mountpoint-s3)
    Finished release [optimized + debuginfo] target(s) in 5m 33s
```

**Comment by dannycjones** [comment]
Hey @karthikraju523.

In the directory of the project (`/root/mountpoint-s3/`), can you try the following?

```
target/release/mount-s3 --version
```

If it outputs a version number, then we know that it is being built to the right location. You then need to have that file/binary in a directory in your `PATH` environment variable to use it without providing the relative path each time.

**Comment by dannycjones** [comment]
Side note - I think we should update the documentation a little bit here to cover that the rest of the instructions in README.md assume it is on the user's `PATH`.

**Comment by karthikraju523** [comment]
Hey dannycjones

Thanks for Reply !!!

Version is popping up as per your instruction. 

root@test:~/mountpoint-s3# target/release/mount-s3 --version

mountpoint-s3 0.2.0-2fade8b

Please guide for further steps .

Good day. Thank you.

**Comment by karthikraju523** [comment]
Hey dannycjones 

Thanks for the support. Now I am able to mount s3 bucket in target PATH.
