### ISSUE TITLE
Feature Request: Official support for AL2023 for the alpha release

### ISSUE THREAD

**Issue by r-heimann** [awslabs/mountpoint-s3#211]
### Tell us more about this new feature.

`The alpha release of Mountpoint for Amazon S3 is only available by building from source, and only supports Linux. These instructions are for Amazon Linux 2, but other Linux distributions should be similar.` AL2023 is in GA, so it would be nice if it would receive official support.

**Comment by dannycjones** [comment]
Thanks @r-heimann for the suggestion.

In lieu of the README being updated, the Dockerfile builds on an AL2023 image so should hopefully detail the dependencies needed.

https://github.com/awslabs/mountpoint-s3/blob/main/docker/Dockerfile#L2-L4

Still leaving the issue open as we should consider updating the README here.

**Comment by jamesbornholt** [comment]
Looks like the only difference for AL2023 is that we need to manually install `git`. #212 will fix the README.

**Comment by dannycjones** [comment]
README.md is updated in a36db96025c19d821c96ddb84b8f77d399f212ea. Closing.
