### ISSUE TITLE
Support for local cache

### ISSUE THREAD

**Issue by massi-ang** [awslabs/mountpoint-s3#251]
### Tell us more about this new feature.

I cannot see how I can configure the amount of space that the cached files can occupy on the local file system, meaning that it might end up using the whole disk with consequences to the stability of the system

**Comment by massi-ang** [comment]
Local cache can be relevant in cases where the local processes need to access the files multiple times during their lifetime. Downloading all the data everytime from S3 would not be efficient. This would be similar to the feature provided by [fscache](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/getting-started-with-fs-cache_managing-file-systems). Cache size, location, and eviction algorithms (such as LRU, LFU, FIFO) should be configurable.

**Comment by jamesbornholt** [comment]
We're evaluating local cache (and other questions around repeated accesses) in #255, so closing this in favor of that issue. Thanks!
