### ISSUE TITLE
"Un-mount" the mounted S3 bucket/folder

### ISSUE THREAD

**Issue by nitinmahawadiwar** [awslabs/mountpoint-s3#259]
### Tell us more about this new feature.

I would like to "Un-mount" the already mounted S3 location.
Business requirement:
1. Applicable when S3 is no longer available.
2. Applicable from Security perspective.

Thanks

**Comment by jamesbornholt** [comment]
Thanks for the suggestion! On Linux, you should be able to unmount an already mounted S3 bucket by running `umount path/to/mount`. So if you originally ran `mount-s3 DOC-EXAMPLE-BUCKET /mnt/s3`, you can run `umount /mnt/s3` to unmount. That will also exit the `mount-s3` process automatically. Does that do what you need?

**Comment by jamesbornholt** [comment]
Going to close this one, but please let us know if we didn't answer your question. Thanks!
