### ISSUE TITLE
Support configuring AWS region via `AWS_REGION`

### ISSUE THREAD

**Issue by dannycjones** [awslabs/mountpoint-s3#274]
### Tell us more about this new feature.

I should be able to configure the region using environment variables.

Specifically, this is the case we should support: `AWS_REGION`.

**Comment by dannycjones** [comment]
Open question: if this is set but the bucket is in a different region, should we correct or fail when we discover this?

I suspect fail.

**Comment by jamesbornholt** [comment]
We'd just use the `AWS_REGION` environment variable as a fallback for the `--region` command-line argument, I think. It should work the same way as `AWS_PROFILE`/`--profile`: prefer the command line argument if provided, otherwise the environment variable if provided, otherwise None.

**Comment by jamesbornholt** [comment]
#422
