### ISSUE TITLE
What is the difference between mountpoint-s3 and other mounts? 

### ISSUE THREAD

**Issue by Tulsishah** [awslabs/mountpoint-s3#319]
### Tell us more about this new feature.

What is the difference between mountpoint-s3 and other mounts like s3fs and goofys?

**Comment by Tulsishah** [comment]
Thanks @jamesbornholt for your answer. I have few questions.
1. How you are measuring the performance ? 
2. Do you have existing dashboard or numbers ? 
3. s3fs fuse can work with other cloud storage buckets also as far as I know, Does mountpoint-s3 will work with other buckets(gcs or Azure)?
4. Are you doing performance tests for all APIs like read or list etc. ?

**Comment by jamesbornholt** [comment]
For your performance questions, I hope our [benchmarking documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/BENCHMARKING.md) can answer them, but let me know if not!

> 3. s3fs fuse can work with other cloud storage buckets also as far as I know, Does mountpoint-s3 will work with other buckets(gcs or Azure)?

Mountpoint is designed for high-throughput access to the Amazon S3 service. While it may be functional against other storage services that use S3-like APIs, we aren't able to provide support for those use cases.

**Comment by jamesbornholt** [comment]
Going to close this issue, but please feel free to open a new one if you have other questions about Mountpoint!
