### ISSUE TITLE
AWS config `credential_process` property support

### ISSUE THREAD

**Issue by hemandee** [awslabs/mountpoint-s3#326]
### Tell us more about this new feature.

Does mountpoint-s3 support custom [credential provider chain](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html#credentialProviderChain)? 

It appears [Appstream](https://docs.aws.amazon.com/appstream2/latest/developerguide/using-iam-roles-to-grant-permissions-to-applications-scripts-streaming-instances.html#how-to-use-iam-role-with-streaming-instances) uses custom profiles and the profile uses Custom Credential Provider CLI.

**Comment by monthonk** [comment]
Thanks for opening the issue, Mountpoint doesn't support the `credential_process` field for providing credentials. We are working to have this fixed and will also update here.

**Comment by monthonk** [comment]
The `credential_process` property should work now from https://github.com/awslabs/mountpoint-s3/pull/351. Would you be able to pull the changes from latest commit and confirm that it's working for you?

**Comment by dannycjones** [comment]
This should now work since #351 was merged introducing `credential_process` into the default credential chain used by Mountpoint. I'll close this issue now.

@hemandee If you are still experiencing problems, please do open a new bug report.
