### ISSUE TITLE
Which aws VM type is best for testing performance of mountpoint-s3 ?

### ISSUE THREAD

**Issue by Tulsishah** [awslabs/mountpoint-s3#383]
### Tell us more about this new feature.

Hi,

I want to do performance tests read, write, and different apis with mountpoint-s3. Please suggest the best aws VM type and storage class.

Thanks,
Tulsi Shah

**Comment by jamesbornholt** [comment]
Hi! We don't have any concrete suggestions for performance testing right now. We've had customers use Mountpoint on a variety of instances and workloads. We do have some [benchmarking documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/BENCHMARKING.md), but it's focused on regression testing.

**Comment by Tulsishah** [comment]
Still can you please suggest  best aws VM type and storage class?

Thanks,
Tulsi Shah

**Comment by jamesbornholt** [comment]
Sorry, I don't think we're well placed to make a suggestion here — we encourage S3 customers to choose the instance type and storage class that are the best fit for their use case. Thanks!
