### ISSUE TITLE
Allow reading already restored Glacier Flexible Retrieval/Glacier Deep Archive objects

### ISSUE THREAD

**Issue by jamesbornholt** [awslabs/mountpoint-s3#434]
### Tell us more about this new feature.

We disabled this in #414 to avoid weird EIO errors because we couldn't distinguish restored objects from unrestored ones without a HeadObject request. But there's a [new S3 feature](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-s3-restore-status-s3-glacier-objects-list-api/) that includes restore status in ListObjectsV2, which we should be able to use to make only restored objects readable (non-000 permissions).

**Comment by odellso** [comment]
Regarding this issue: I am quite keen to have this enhancement released. Apologies if this is not the proper git etiquette (not a professional developer myself), but is there anything I can do to push this along? Would be happy to contribute at-scale user testing if that would help.

**Comment by jamesbornholt** [comment]
@odellso we actually have an open PR for this right now (#467) that should be merged shortly. You'll still have to manually issue restore requests for the objects, but once they're restored they'll be readable with Mountpoint. Does that fit your use case?

**Comment by odellso** [comment]
> @odellso we actually have an open PR for this right now (#467) that should be merged shortly. You'll still have to manually issue restore requests for the objects, but once they're restored they'll be readable with Mountpoint. Does that fit your use case?

@jamesbornholt: thank you for the reply, that's great news. Yes, our use case is exactly as you have described.

**Comment by jamesbornholt** [comment]
#467 is merged and released as v1.0.1: https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-1.0.1
