### ISSUE TITLE
Download a specific version of mountpoint-s3?

### ISSUE THREAD

**Issue by nickvollmar** [awslabs/mountpoint-s3#448]
### Tell us more about this new feature.

Hello,

Is it possible to obtain a download URL for a specific version of mountpoint-s3? 

All of the URLs I saw in the documentation point to the `latest` version, e.g.
```
https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.deb
```
For production deployments, I'd like to pin the version. 

(I tried using that URL but replacing "latest" with "1.0.0" or "v1.0.0", which resulted in 403s.)

Thank you!

**Comment by dannycjones** [comment]
Hey @nickvollmar.

You can download a specific version using the links in the GitHub release: https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-1.0.0

For example, the DEB URL would be:

```
https://s3.amazonaws.com/mountpoint-s3-release/1.0.0/x86_64/mount-s3-1.0.0-x86_64.deb
```

The pinned versions do include the version number and architecture in the final file name.

**Comment by nickvollmar** [comment]
Perfect! I did not think to check there. Thank you very much.
