### ISSUE TITLE
Git lfs clone operation Fails on S3 Mounted Directory due to Unsupported File Operations

### ISSUE THREAD

**Issue by NasonZ** [awslabs/mountpoint-s3#449]
### Mountpoint for Amazon S3 version

mount-s3 1.0.0

### AWS Region

eu-central-1

### Describe the running environment

Running on a local machine (ubuntu 22.04).

### What happened?

I attempted to clone a large (14GB) huggingface git repository into a directory mounted using mount-s3 via git lfs. The operation failed with errors related to file operations unsupported by the S3 mount, such as symbolic references and file locking. I expected the git clone operation to complete without errors.

**Steps to Reproduce**
1. Mount an S3 bucket using `mount-s3`.
2. Navigate to the mounted directory.
3. Attempt to clone a git repository into the mounted directory via 
```
git lfs install
git clone https://huggingface.co/meta-llama/Llama-2-7b
```
4. Observe the aforementioned errors.

### Relevant log output

```shell
$ git clone https://huggingface.co/meta-llama/Llama-2-7b
Cloning into 'Llama-2-7b'...
warning: unable to unlink '/home/me/AWS/s3_mount/Llama-2-7b/.git/HEAD.lock': Operation not permitted
error: unable to write symref for HEAD: Function not implemented
```

**Comment by jamesbornholt** [comment]
Unfortunately `git clone` requires `rename`, which Mountpoint doesn't support. You can probably move the large model files into Mountpoint after cloning the repo onto local storage, but the Git repo itself won't be able to easily live in Mountpoint. Sorry about that!

**Comment by NasonZ** [comment]
Thanks for the explanation, the repo's I'm looking to clone can be quite large (10-200GB) so I want to avoid downloading them locally and then re-uploading them. I hoped that I would be able to clone them into a mounted repo to save time.
