### ISSUE TITLE
Is S3-Mountpoint suitable as Database backup Destination?

### ISSUE THREAD

**Issue by picoroma** [awslabs/mountpoint-s3#462]
### Tell us more about this new feature.

For Database like Oracle or DB2 or MSSQL ?
(I meaning at SAP application Database)
Can I mount S3 as local file system and use this as direct backup destination?
Usually I perform the backup locally and AFTER (step2) copy\move the backup to S3.
Can I delete\remove the step2 for my backups ?

**Comment by sauraank** [comment]
Hi! If you dont need to modify/overwrite the Database backup, Mountpoint should work fine for it. To use it with Mountpoint, you will need to have backup in a S3 bucket. Does this help?

**Comment by dannycjones** [comment]
As Ankit shared, if you're not modifying the data outside of writing sequentially to it in one go then you should be fine. If you need to write non-sequentially or close and reopen for writing, then Mountpoint won't be able to support that use case at this time.

Closing this, please re-open if you have any additional questions.
