### ISSUE TITLE
Add support for caching

### ISSUE THREAD

**Issue by tchaton** [awslabs/mountpoint-s3#463]
### Tell us more about this new feature.

Hey @jamesbornholt and al,

It would be great to add support for VFS caching to mountpoint-s3. When the datasets fits entirely on the machine, it would be great to have a mechanism to cache it on the machine to avoid making further training epochs slower.

Best,
T.C

**Comment by jamesbornholt** [comment]
Yeah, caching is something we're looking into. It's a little tricky because it conflicts with S3's strong consistency model, but for workloads like ML training the bucket is probably static so consistency doesn't matter. We're tracking this on our roadmap in #255. Thanks for the suggestion!
