### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by crowecawcaw** [awslabs/mountpoint-s3#468]
### Tell us more about this new feature.

It would be wonderful if Mountpoint supported symlinks.

Mountpoint has a tenet of only supporting features which are native to S3, and at first glance symlinks do not seem native. (They're even called out explicitly in the README.) But as a counter example, S3 uses the [`x-amz-website-redirect-location` metadata value](https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html) for supporting redirects for its static websites feature. A Mountpoint symlink could reuse this same metadata key or another another one to point to another file / object.

One barrier to supporting symlinks based on metadata values is that a FUSE interface needs to show if a file is a symlink when listing files in a directory, and the corresponding S3 API ListObjectsV2 does not return metadata. This gap could be addressed by updating ListObjectsV2 to optionally return the `x-amz-website-redirect-location` value in its response. As a precedent and example, see how [ListObjectsV2 optionally returns objects' owners](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax) if `fetch-owners` is set to `True`.

Symlink support would be especially useful for Mountpoint as an alternative to moving or renaming files since renaming is not supported by S3. It would increase compatibility with existing workflows and filesystems that use symlinks.

We can also gauge demand for the feature by seeing how it's supported by many other POSIX/S3 translation layers including [AWS DataSync](https://docs.aws.amazon.com/datasync/latest/userguide/special-files-copied.html), [Amazon FSx](https://docs.aws.amazon.com/fsx/latest/LustreGuide/autoexport-data-repo-dra.html), [S3FS](https://github.com/s3fs-fuse/s3fs-fuse), [rclone](https://rclone.org/local/), and [GCS FUSE](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#symlink-inodes) despite the workarounds it currently requires.

**Comment by ahmarsuhail** [comment]
Thanks for opening this issue @crowecawcaw, since this requires server side changes to ListObjectsV2, this isn't on our roadmap for now, but something we'd reconsider revisiting in the future. I am closing this for now.
