### ISSUE TITLE
Mounting in ECS / EC2 does not expose to other containers

### ISSUE THREAD

**Issue by ktruckenmiller** [awslabs/mountpoint-s3#472]
### Mountpoint for Amazon S3 version

mount-s3 1.0.0

### AWS Region

us-west-2

### Describe the running environment

Having trouble running a sidecar container where the mount is accessible in the other. 

Running on Amazon Linux ECS EC2 

Task definition is as follows

```
{
"containerDefinitions": [
        {
            "name": "mountpoint",
            "image": "ktruckenmiller/aws-mountpoint-s3",
            "cpu": 0,
            "memory": 70,
            "essential": true,
            "environment": [
                {
                    "name": "S3_BUCKET",
                    "value": "my-bucket"
                },
                {
                    "name": "S3_MOUNTPOINT",
                    "value": "/mountpoint/my-bucket"
                }
            ],
            "mountPoints": [
                {
                    "sourceVolume": "my-bucket",
                    "containerPath": "/mountpoint",
                    "readOnly": false
                }
            ],
            "linuxParameters": {
                "devices": [
                    {
                        "hostPath": "/dev/fuse",
                        "containerPath": "/dev/fuse",
                        "permissions": [
                            "read",
                            "write"
                        ]
                    }
                ],
            },
            "privileged": true
        },
        {
            "name": "list-s3",
            "image": "alpine",
            "cpu": 0,
            "memory": 30,
            "essential": true,
            "mountPoints": [
                {
                    "sourceVolume": "my-bucket",
                    "containerPath": "/mountpoint/my-bucket",
                    "readOnly": false
                }
            ],
            "dependsOn": [
                {
                    "containerName": "mountpoint",
                    "condition": "START"
                }
            ]
        }
    ]
}

```

I run this, but the other container lists an empty volume. 

### What happened?

I expected it to list the s3 files. 

The files are available in the aws-mountpoint-s3 container, just not in the alpine one.

Example code in this repo
https://github.com/ktruckenmiller/aws-mountpoint-s3

**Comment by monthonk** [comment]
Hi, did you get any errors while starting the alpine container? There is an issue in v1.0.0 where `--allow-root` and `--allow-other` can't be used together (https://github.com/awslabs/mountpoint-s3/pull/466). I see that you're using both in `entrypoint.sh`.

**Comment by monthonk** [comment]
Looking at a similar issue on EKS (https://github.com/awslabs/mountpoint-s3/issues/364), I think we also need something equivalent to `mountPropagation: Bidirectional` on EKS mount configuration but not sure if it's supported on ECS.

**Comment by ktruckenmiller** [comment]
It looks like I'm using the amazonlinux container, so I don't believe that's alpine. For the propagation testing, I'm using a scratch image to mount the volume and looking for files. Also looking on the ec2 host to see if the files are there as well and those aren't propagated either to that location.  

The only location those files are available in are the container that is adding the fuse directory - not on the host or the other ECS tasks that share the directory. 

The error I get on ECS when I use the `--allow-other` is

```
1: CRT error 1048: aws-c-io: AWS_IO_SOCKET_TIMEOUT, socket operation timed out.
0: Unknown CRT error
```

Even though I use the root user when listing directories on the host.

**Comment by monthonk** [comment]
That seems like a connection problem. Can you make sure there is a route from your container to S3?

I ran into `AWS_IO_SOCKET_TIMEOUT` too but after changing network mode to `host` and adding `:shared` to the container path, I managed to make it work. Here is my task definition.
```
"containerDefinitions": [
        {
            "name": "mountpoint-s3",
            "image": "<my_private_image>",
            "cpu": 0,
            "essential": true,
            "environment": [
                {
                    "name": "S3_BUCKET",
                    "value": "<my_s3_bucket>"
                },
                {
                    "name": "S3_MOUNTPOINT",
                    "value": "<mount_path>/<my_s3_bucket>"
                }
            ],
            "mountPoints": [
                {
                    "sourceVolume": "test-volume",
                    "containerPath": "<mount_path>/:shared",
                    "readOnly": false
                }
            ],
            "volumesFrom": [],
            "linuxParameters": {
                "devices": [
                    {
                        "hostPath": "/dev/fuse",
                        "containerPath": "/dev/fuse",
                        "permissions": [
                            "read",
                            "write"
                        ]
                    }
                ]
            },
            "privileged": true
        },
        {
            "name": "alpine",
            "image": "<my_alpine_image>",
            "cpu": 0,
            "essential": false,
            "mountPoints": [
                {
                    "sourceVolume": "test-volume",
                    "containerPath": "/tmp/mnt/"
                }
            ],
            "volumesFrom": [
                {
                    "sourceContainer": "mountpoint-s3",
                    "readOnly": false
                }
            ],
            "dependsOn": [
                {
                    "containerName": "mountpoint-s3",
                    "condition": "START"
                }
            ]
        }
    ]
```

**Comment by tchaton** [comment]
Hey @ktruckenmiller,

I managed to do this on EC2 using a subpath of the docker binded mount. It seems mountpoint-s3 complained the mount already existed.

**Comment by ktruckenmiller** [comment]
@monthonk what was your volume config on the task definition?

**Comment by monthonk** [comment]
Sorry for late reply, I have configured a bind mount volume type to path `/home/ec2-user/shared`.

**Comment by sauraank** [comment]
I am closing this issue for now due to inactivity. If you have any further questions, please re-open this issue or open a new issue.
