### ISSUE TITLE
PHP DirectoryIterator returns no files and triggers a "readdirplus failed" error

### ISSUE THREAD

**Issue by ale-rinaldi** [awslabs/mountpoint-s3#477]
### Mountpoint for Amazon S3 version

mount-s3 1.0.0

### AWS Region

eu-west-1

### Describe the running environment

Running in EC2 on Ubuntu with static access and secret key configured via awcli

### What happened?

- I created a test mount folder: `mkdir /home/ubuntu/mount`
- I mounted a bucket with some files in it: `mount-s3 my-test-bucket /home/ubuntu/mount`
- I ensured my files show on ls: `ls /home/ubuntu/mount` (list of files appears)
- I installed PHP cli: `sudo apt install php-cli`
- I created this PHP script:
```php
<?php
$count = 0;
foreach (new \DirectoryIterator("/home/ubuntu/mount") as $fileInfo) {
    echo "Found file: " . $fileInfo->getFilename() . "\n";
    $count++;
}
echo "$count files found\n";
```
- I launched the script: `php test.php`

Of course, I expected the list and count of files, but I get a "0 files found" instead.

When I run the script, a warning gets logged on syslog (pasted below). I tried multiple times with the same result, only "req=" and "fh=" values change.

### Relevant log output

```shell
mount-s3[8770]: [WARN] readdirplus{req=30 ino=1 fh=3 offset=0}: mountpoint_s3::fuse: readdirplus failed: offset mismatch, expected=8, actual=0
```

**Comment by ahmarsuhail** [comment]
Looking at the debug logs, with `DirectoryIterator`, it sends an initial ` READDIRPLUS fh FileHandle(1), offset 0, size 4096`, and then when after this request completes, it's next request is also `READDIRPLUS fh FileHandle(1), offset 0, size 4096`. That is, offset is 0, which causes the error. For the second request, it should be > 0, depending on how many files were read in the first request. 

I tested with the following script:

```
<?php
$path = "/home/ubuntu/mnt";
$count = 0;
if ($handle = opendir($path)) {
    while (false !== ($file = readdir($handle))) {
        echo "Found file: " . $file . "\n";
        $count++;
    }
    echo "$count files found\n";
    closedir($handle);
}
```

and this works ok, and the offsets are set correctly. could you use this as a workaround?

**Comment by ale-rinaldi** [comment]
Hello,

thanks for your answer.

Yeah, this is a viable workaround since it's code I have control on, thank you.

However, I can see that the DirectoryIterator is usually working, even with other S3 mount software. Maybe it's the response that Mountpoint gives to readdirplus that makes DirectoryIterator do subsequent calls with wrong offset? I think it's still worth investigating, since the DirectoryIterator could still be in some vendored code and this would be a mess :)

Thanks!
