### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by cr-solutions** [awslabs/mountpoint-s3#490]
### Mountpoint for Amazon S3 version

mount-s3 1.0.0

### AWS Region

eu-west-1

### Describe the running environment

Hello, we tried out the mount-s3 as an alternative for goofys.

we mounting the bucket similar like with goofys

sudo mount-s3 --allow-delete --allow-other --uid=1000 --gid=33 --dir-mode=0777 --file-mode=0777 my-bucket /mnt/s3/www

editig files direct with linux tools like vi seems working, but if we access the files from a PHP CLI tool we get errors, please see the output

any ideas we do something wrog here?
or is it a known bug?

best regards
Ricardo

### What happened?

editig files direct with linux tools like _vi_ seems working, but if we access the files from a PHP CLI tool we get the errors, please see the output

### Relevant log output

```shell
`08:47:03 WARNING   [php] Warning: rmdir(/var/www/sw.arendicom.de/public/theme/111dc88bcb3d026824fb8be5e400cee6): Operation not permitted ["exception" => ErrorException { …}]
08:47:07 WARNING   [php] Warning: file_put_contents(/var/www/sw.arendicom.de/public/theme/111dc88bcb3d026824fb8be5e400cee6/css/all.css): failed to open stream: Operation not permitted ["exception" => ErrorException { …}]
08:47:07 WARNING   [php] Warning: file_put_contents(/var/www/sw.arendicom.de/public/theme/111dc88bcb3d026824fb8be5e400cee6/js/all.js): failed to open stream: Operation not permitted ["exception" => ErrorException { …}]
08:47:07 WARNING   [php] Warning: fopen(/var/www/sw.arendicom.de/public/bundles/storefront/assets/illustration/404_error.svg): failed to open stream: Operation not permitted ["exception" => ErrorException { …}]
08:47:07 WARNING   [php] Warning: fopen(/var/www/sw.arendicom.de/public/theme/111dc88bcb3d026824fb8be5e400cee6/assets/illustration/404_error.svg): failed to open stream: Operation not permitted ["exception" => ErrorException { …}]`
```

debug output I found from fuse
`2023-08-31T09:11:30.693819Z  WARN open{req=48 ino=11}: mountpoint_s3::fuse: open failed: inode error: inode 11 (full key "sw.arendicom.de/public/theme/111dc88bcb3d026824fb8be5e400cee6/js/all.js") is not writable`

**Comment by cr-solutions** [comment]
addendum:
read and touch with linux is working, but also saveing a change with _vi_ throws an error
`"public/theme/111dc88bcb3d026824fb8be5e400cee6/css/test.foo" E212: Can't open file for writing`

**Comment by monthonk** [comment]
Hi, Mountpoint doesn't support modifying existing files (see our [semantics documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#writes)). The reason vi is working is a bit complicated. If the file is small enough, all the changes will be in-memory, vi will then delete the existing file and write all contents to a new file in one go.

**Comment by cr-solutions** [comment]
@monthonk Okey, thanks for this hint, so it isend't are replacement for ggofys this time ...
