### ISSUE TITLE
Can not write more than 80gb file to mount point

### ISSUE THREAD

**Issue by swiftfwi** [awslabs/mountpoint-s3#498]
### Mountpoint for Amazon S3 version

mount-s3 1.0.1

### AWS Region

us-east-1

### Describe the running environment

using a c7g.8xlarge in us-east-1 region, "mount-s3 --allow-delete" was used. 

### What happened?

using a c7g.8xlarge in us-east-1 region, "mount-s3 --allow-delete" was used. When the file size is larger than 80gb. my application will run into "file is too large" error. I could repeat this error with just cp command.

**Comment by jamesbornholt** [comment]
Yes, there's an 80GB limit on uploads by default. You can increase it with the `--part-size` parameter; see the docs: https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#maximum-object-size

**Comment by monthonk** [comment]
I'm closing this issue since the part-size config should fix your problem. It should work by default once we implemented dynamic part size feature (#451), we will keep you updated on that thread .
