### ISSUE TITLE
enable CAT command on s3 mountpoint 

### ISSUE THREAD

**Issue by sachinsapkale** [awslabs/mountpoint-s3#499]
### Tell us more about this new feature.

I would like to perform CAT operation on the files that I am able to view on filesystem hosted using mountpoint-s3

**Comment by passaro** [comment]
Hi. `cat` should generally work on files served by mountpoint. Are you seeing any specific issue with it? If so, any details about the command and the files you are trying to read may help (together with the relevant logs - see [here](https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md) for details).

**Comment by passaro** [comment]
Closing as already implemented. Please open a new issue if you have specific problems with the `cat` command.
