### ISSUE TITLE
Write not available for S3 compatible - Cloudian Objectstorage

### ISSUE THREAD

**Issue by AngeloFarina** [awslabs/mountpoint-s3#515]
### Mountpoint for Amazon S3 version

mount-s3 1.0.1

### AWS Region

We use an on premise S3 compatible Objectstorage, Cloudian

### Describe the running environment

We use a S3 compatible objectstorage called Cloudian Hyperstore.
The Cloudian cluster is running on premise with a cluster of multiple CentOS Linux release 7.9.2009 (Core).
We installed the mount-s3 on our personal VMs running Red Hat Enterprise Linux release 8.8 (Ootpa).

### What happened?

On our Cloudian Objectstorage we can create an account and generate the aws_access_key_id and the aws_secret_access_key. Then configure everything properly on our VMs system on ~/.aws/credentials and ~/.aws/config
I use aws_cli and all the functionalities are working correctly but when i use the mount-s3 I'm only able to list the files on a bucket and delete them if the flag --allow-delete is set when mounting.

Copying or moving files on the mount will result in a 403 error, saying to "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method."

### Relevant log output

```shell
Sep 14 11:20:00 my_vm mount-s3[3584971]: [WARN] lookup{req=18 ino=1 name="access.json"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Sep 14 11:20:00 my_vm mount-s3[3584971]: [WARN] create{req=20 parent=1 name="access.json"}: mountpoint_s3::fuse: create failed: operation not supported by Mountpoint
Sep 14 11:20:01 my_vm mount-s3[3584971]: [WARN] getxattr{req=26 ino=2 name="security.capability"}: mountpoint_s3::fuse: getxattr failed: operation not supported by Mountpoint
Sep 14 11:20:01 my_vm mount-s3[3584971]: [WARN] flush{req=30 ino=2 fh=2}: mountpoint_s3::fuse: flush failed: operation not supported by Mountpoint
Sep 14 11:20:01 my_vm mount-s3[3584971]: [WARN] open{req=24 ino=2}:put_object{id=10 bucket=testing key=access.json}: mountpoint_s3_client::s3_crt_client: request failed request_type=UploadPart http_status=403 range=None duration=305.900674ms ttfb=Some(300.559527ms) request_id=xxx
Sep 14 11:20:02 my_vm mount-s3[3584971]: [WARN] open{req=24 ino=2}:put_object{id=10 bucket=testing key=access.json}: mountpoint_s3_client::s3_crt_client: meta request failed duration=1.493716688s error=ClientError(Forbidden("The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details."))
Sep 14 11:20:02 my_vm mount-s3[3584971]: [WARN] release{req=32 ino=2 fh=2}: mountpoint_s3::fuse: release failed: put failed: Client error: Forbidden: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.
```

**Comment by jamesbornholt** [comment]
This one might be hard for us to offer much help for, since we're not familiar with Cloudian. You might be able to debug this by using [verbose logging](https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md#verbose-logging), and specifically the `--debug-crt` option, which will log the signing strings and signatures that Mountpoint calculates for requests. Then (at least for Amazon S3) the verbose version of the error message you provided usually also includes what the server calculated for signing strings and signatures. The verbose error message should also be logged with the `--debug-crt` option, so you can compare the two.

**Comment by monthonk** [comment]
We are closing this issue. Please feel free to reopen if you have further information.

**Comment by AngeloFarina** [comment]
I'm now working with **mount-s3 1.4.0**.
I have some more information that might help defining the issue.

```
Feb 15 16:09:01 my-vm mount-s3[1571818]: [INFO] release{req=92 ino=5 fh=6 name=file.txt}: log: (id=0x7f0dd809b9c0) Signing successfully built canonical request for algorithm SigV4, with contents #012PUT#012/a.txt#012partNumber=1&uploadId=MmUxM2E2MzI5MTE3MDgwMDk3NDE3NTI#012accept:application/xml#012content-encoding:aws-chunked#012content-length:37#012host:bucket.ourhost#012x-amz-content-sha256:STREAMING-UNSIGNED-PAYLOAD-TRAILER#012x-amz-date:20240215T150901Z#012x-amz-decoded-content-length:0#012x-amz-trailer:x-amz-checksum-crc32c#012#012accept;content-encoding;content-length;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-trailer#012STREAMING-UNSIGNED-PAYLOAD-TRAILER

Feb 15 16:09:01 my-vm mount-s3[1571818]: [INFO] release{req=92 ino=5 fh=6 name=file.txt}: log: (id=0x7f0dd809b9c0) Signing successfully built string-to-sign via algorithm SigV4, with contents #012AWS4-HMAC-SHA256#01220240215T150901Z#01220240215/myregion/s3/aws4_request#012c248c4e2b29f55c094b50691a55fba6b2091b2a9846797e63fba517e8d10fa46

Feb 15 16:09:01 my-vm mount-s3[1571818]: [INFO] release{req=92 ino=5 fh=6 name=file.txt}: log: (id=0x7f0dd809b9c0) Http request successfully built final authorization value via algorithm SigV4, with contents #012AWS4-HMAC-SHA256 Credential=myaccessid/20240215/myregion/s3/aws4_request, SignedHeaders=accept;content-encoding;content-length;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-trailer, Signature=9095dcb27e05077937de47f2331af86538c2c64ba65b8879c3fc378125d2f1aa

Feb 15 16:09:01 my-vm mount-s3[1571818]: [INFO] log: id=0x559a889005d0 Requests-in-flight(approx/exact):1/1  Requests-preparing:0  Requests-queued:0  Requests-network(get/put/default/total):0/1/0/1  Requests-streaming-waiting:0  Requests-streaming-response:0  Endpoints(in-table/allocated):1/1

Feb 15 16:09:01 my-vm mount-s3[1571818]: [ERROR] log: id=0x7f0dd802afb0 Meta request cannot recover from error 14343 (Invalid response status from request). (request=0x7f0df801be20, response status=403)

Feb 15 16:09:01 my-vm mount-s3[1571818]: [INFO] log: id=0x7f0df0025fb0: Shutting down connection with error code 0 (AWS_ERROR_SUCCESS).
```


Those appear to be the recurring steps, followed by this error

`Feb 15 16:09:02 my-vm mount-s3[1571818]: [WARN] release{req=92 ino=5 fh=6 name=file.txt}:put_object{id=28 bucket=mybucket key=a.txt}: mountpoint_s3_client::s3_crt_client: meta request failed duration=1.235436649s error=ClientError(Forbidden("The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details."))`

Do you think this is due to a bug of Cloudian in handling the signature check?

**Comment by jamesbornholt** [comment]
I'm not super familiar with Cloudian, but if it's only writes that are failing like this, one possibility is that it may not support [S3's additional checksums feature](https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/), which Mountpoint requires for writes. They're specified with the `x-amz-checksum-crc32c` header. We're tracking the ability to turn off additional checksums in #516, but it's not something we're currently working on.

**Comment by AngeloFarina** [comment]
Hi @jamesbornholt I checked on the documentation of Cloudian and indeed this header it's not mentioned anywhere.

**Comment by AngeloFarina** [comment]
Hi all!
I wanted to inform you that this bug is now fixed on Cloudian's side. There was indeed the x-amz-checksum-crc32c header missing.

Now put operations work.

Tested on mountpoint version 1.5

**Comment by dannycjones** [comment]
> Hi all! I wanted to inform you that this bug is now fixed on Cloudian's side. There was indeed the x-amz-checksum-crc32c header missing.
> 
> Now put operations work.
> 
> Tested on mountpoint version 1.5

Thanks for sharing, Angelo! Glad to hear you're having success with your use case.
