### ISSUE TITLE
Amazon S3 on Outposts support for write workloads

### ISSUE THREAD

**Issue by knichwitz** [awslabs/mountpoint-s3#516]
### Tell us more about this new feature.

I would like to have the possibility to use S3 Mountpoint on AWS Outpost.

This would help to reduce costs for EBS on configuration Outpost Racks.

EBS is up to 3x more expensive than S3 Storage on AWS Outpost. Running Machine Learning use cases at scale with S3 Mountpoint, would support many users in configuring cost efficient AWS Outpost Racks

**Comment by ahmarsuhail** [comment]
Hey, thanks for opening this issue. As of `v1.0.1`, Mountpoint should work with outposts in read only mode. You can enable this by passing in  `--read-only` during mount time. Currently Mountpoint does not work with Outposts for writes as Outposts does not support additional checksums. We plan to enable write support for Outposts and will share here when we have an update.

**Comment by jamesbornholt** [comment]
Writes to Outposts buckets should work in the next Mountpoint release!

**Comment by MrFishFinger** [comment]
hi @jamesbornholt - amazing, love your work!

`--upload-checksums=off` also seems to fix writing to a B2 backblaze bucket:

```
❯ mount-s3 --endpoint-url=https://s3.eu-central-003.backblazeb2.com --upload-checksums=off  test-b2-bucket /mnt/s3/test-b2-bucket
bucket test-b2-bucket is mounted at /mnt/s3/test-b2-bucket

❯ touch /mnt/s3/test-b2-bucket/test2.txt

❯ ls -lh /mnt/s3/test-b2-bucket/
insgesamt 0
-rw-r--r-- 1 user user 0 Mai 24 21:34 test1.txt
-rw-r--r-- 1 user user 0 Mai 24 21:36 test2.txt
```

(i used an [unofficial deb package](https://github.com/awslabs/mountpoint-s3/actions/runs/9189184243/artifacts/1526387350) built in a recent `main` [CI job](https://github.com/awslabs/mountpoint-s3/actions/runs/9189184243/job/25270674663))

**Comment by metadaddy** [comment]
I just verified that [Mountpoint for Amazon S3 version 1.7](https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-1.7.0) works with B2:

```console
# mount-s3 --endpoint-url=https://s3.us-west-004.backblazeb2.com/ --upload-checksums=off metadaddy-mountpoint ./tester
bucket metadaddy-mountpoint is mounted at ./tester
# cp mount-s3.deb ./tester
# ls -l tester
total 10511
-rw-r--r-- 1 root root 10762814 Jun 11 01:29 mount-s3.deb
```

![Screenshot of file in Backblaze B2 web UI](https://github.com/awslabs/mountpoint-s3/assets/723517/349c944c-15c8-42a9-b5c1-218f79a4360a)
