### ISSUE TITLE
Cannot mount due to difference between request time and current time too large (RequestTimeTooSkewed)

### ISSUE THREAD

**Issue by seisowl** [awslabs/mountpoint-s3#518]
### Mountpoint for Amazon S3 version

mount-s3 1.0.1

### AWS Region

us-east-1

### Describe the running environment

Windows 11 WSL with Ubuntu 22.04.2 LTS

### What happened?

I was able to mount the s3 last night then after I carried the laptop around the network resets.
I had to umount  it then mount again and this error message shows.

ps: I am traveling and the timezone is 8 hours different than us-east but I think it's irrelevant.

### Relevant log output

```shell
Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket XXXX in region us-east-1
    1: Client error
    2: Forbidden: The difference between the request time and the current time is too large.
Error: Failed to create mount process
```

**Comment by jamesbornholt** [comment]
I'm going to close this issue, but please feel free to reopen if this happens again and the debugging steps in @dannycjones's comment above don't help!
