### ISSUE TITLE
Mac OS Support

### ISSUE THREAD

**Issue by ngander64** [awslabs/mountpoint-s3#519]
### Tell us more about this new feature.

I would like to see support for Mac OS. It's debatable whether that would include x86 or not at this point as that architecture is obviously on the way out. Of course, it will still be around for several years yet.

**Comment by dannycjones** [comment]
Thanks for the feature request, @ngander64!

We do already have a request open for macOS support (#444), so I'll close this issue in favor of tracking that one. Please do add a thumbs up to that issue to show interest in the feature.
