### ISSUE TITLE
Cannot see mounted folders in Midnight Commander 

### ISSUE THREAD

**Issue by dirkpetersen** [awslabs/mountpoint-s3#520]
### Mountpoint for Amazon S3 version

mount-s3 1.0.1

### AWS Region

us-west-2

### Describe the running environment

Running Amazon Linux 2023 in EC2 with midnight commander (install mc package)

### What happened?

I mount a bucket and can see folders

```
ec2-user@froster:/mnt/s3/froster$ ls -l
total 0
drwxr-xr-x. 2 root root 0 Sep 16 22:27 archive
drwxr-xr-x. 2 root root 0 Sep 16 22:27 deep_archive
```

but when running standard mc there is nothing there:

![image](https://github.com/awslabs/mountpoint-s3/assets/1427719/075debd9-efb2-4e00-9402-d9228908fee7)

Btw: I noticed that df is reporting all zeros, while this may be correct many other fuse programmers have stumbled over this you might give it 1EB of size and also 1EB of free space just for compatibility reasons ?

```
ec2-user@froster:/mnt/s3/froster$ df -h /mnt/s3/froster
Filesystem      Size  Used Avail Use% Mounted on
mountpoint-s3      0     0     0    - /mnt/s3/froster
```

**Comment by monthonk** [comment]
Thanks for reporting. Are you able to try implementing the `statfs` operation (https://docs.rs/fuser/latest/fuser/trait.Filesystem.html#method.statfs) and see if that solve your issue?

**Comment by dirkpetersen** [comment]
Sorry, I am not really able to code around in Rust right now. The issue is really easy to reproduce by trying mc

**Comment by monthonk** [comment]
I did try implementing `statfs` this week and can confirm that it's not the root cause.

From my simple test, the problem seems to be with `readdirplus` operation. mc is sending out-of-order `readdirplus` requests to Mountpoint and got rejected.

For example, the sequence of requests from ls command looks like this
```
fuser::request: FUSE( 56) ino 0x0000000000000001 READDIRPLUS fh FileHandle(5), offset 0, size 4096
fuser::request: FUSE( 58) ino 0x0000000000000001 READDIRPLUS fh FileHandle(5), offset 4, size 4096
```

Instead this is what I got when running mc
```
fuser::request: FUSE( 20) ino 0x0000000000000001 READDIRPLUS fh FileHandle(2), offset 0, size 4096
fuser::request: FUSE( 22) ino 0x0000000000000001 READDIRPLUS fh FileHandle(2), offset 0, size 4096
readdirplus{req=22 ino=1 fh=2 offset=0}: mountpoint_s3::fuse: readdirplus failed: offset mismatch, expected=4, actual=0
```
