### ISSUE TITLE
Files open for writing in excess of five minutes will result in a panic

### ISSUE THREAD

**Issue by dannycjones** [awslabs/mountpoint-s3#523]
In one of the changes to mountpoint-s3's metrics, we added an upper bound to histogram values of 300M. When measuring duration, we sometimes use microseconds which would result in values of 5 minutes or more exceeding this upper bound, and the error for this was not handled.

The fix (b89117ad1384490a3c226e9f7cd90ec1b6d19124) is already in `main` branch if building from source, but is present in the v1.0.1 release.

**Comment by jamesbornholt** [comment]
The fix for this was released in [v1.0.2](https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-1.0.2).
