### ISSUE TITLE
Random writes "Operation not permitted" on ffmpeg workload

### ISSUE THREAD

**Issue by juanmarti81** [awslabs/mountpoint-s3#524]
### Mountpoint for Amazon S3 version

mount-s3 v1.0.1

### AWS Region

eu-west-1

### Describe the running environment

EC2 instance with ami-05d85d6a2eb899fc4
ECS container ubuntu 20.04

### What happened?

I'm trying to write a transcoded video file with ffmpeg. I can read the file, start the transcoding but can't write it back to the mounted location.

I'm mounting the bucket in my code:
`
os.makedirs("/mnt/devops", mode=777, exist_ok=True)
subprocess.run(["mount-s3", "--allow-delete", "--allow-other", "--dir-mode", "777","devops", "/mnt/devops"], check=True)
`

I confirm i can access to the file:
`
if input_url:
if not os.path.isfile("/mnt/devops/" + input_url):
logging.error("Input file does not exist")
sys.exit(1)
logging.info("Input file exists")
`

the role attached to the container has S3FullAccess policy

### Relevant log output

```shell
INFO:root:Starting the ffmpeg wrapper
bucket devops is mounted at /mnt/devops
INFO:root:Input file exists
INFO:root:ffmpeg command to launch : ffmpeg -i /mnt/devops/Mezz_038772_PAR_AssassinClub_TR_HD_VLAS.mpg -max_muxing_queue_size 4096 -c:v mpeg2video -pix_fmt yuv420p -g 12 -bf 2 -sc_threshold 1G -profile:v main -level 4.1 -aspect 16:9 -vf scale=1920:1080 -b:v 10M -minrate 10M -maxrate 10M -r 24000/1001 -c:a mp2 -ar 48000 -rematrix_maxval 1.0 -ac 2 -b:a 256k -y /mnt/devops/038772_PAR_AssassinClub_TR_HD_VLAS_3.mpg
ERROR:root:ffmpeg failed - return code : 1
ERROR:root:ffmpeg failed - output : 
ERROR:root:ffmpeg failed - error : ffmpeg version 5.1.3 Copyright (c) 2000-2022 the FFmpeg developers
"Input #0, mpeg, from '/mnt/devops/Mezz_038772_PAR_AssassinClub_TR_HD_VLAS.mpg':"
"Duration: 00:02:18.00, start: 0.409456, bitrate: 31212 kb/s"
"Stream #0:0[0x1e0]: Video: mpeg2video, yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30000 kb/s, 23.98 fps, 23.98 tbr, 90k tbn"
Side data:
cpb: bitrate max/min/avg: 30000000/0/0 buffer size: 9781248 vbv_delay: N/A
"Stream #0:1[0x1c0]: Audio: mp2, 48000 Hz, stereo, fltp, 256 kb/s"
/mnt/devops/038772_PAR_AssassinClub_TR_HD_VLAS_3.mpg: Operation not permitted
```

**Comment by juanmarti81** [comment]
I've been doing several tests as i'm not an expert on docker and linux.

I managed to generate the logs save them to the bucket. But as i copy pasted everything, I added boto3 to do it. When i did this, it started to work and I had the output from ffmpeg.
I added:
```
import boto3

session = boto3.Session(aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
                        aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
                        region_name="eu-west-1")
s3 = session.resource("s3")
```
```
subprocess.run(["mount-s3", "--allow-delete", "--allow-other", "--dir-mode", "777", "--debug", "devops", "/mnt/devops", "-l", "/var/log/syslog"], check=True)
```
```
for file in os.listdir("/var/log/syslog"):
     s3.Object("devops", file).upload_file("/var/log/syslog/{}".format(file))
     logging.info("Uploading file %s to s3", file)
```

To know what changed, I removed the parts to save the log. It still worked. Only left the import and the session.

I removed boto3 import... it didn't work anymore.

I added everything back... it works. So, is it needed to have boto3 imported?

![image](https://github.com/awslabs/mountpoint-s3/assets/46056491/5046e34f-0db5-4c25-8b05-337661cc547b)

**Comment by dannycjones** [comment]
There shouldn't be any interaction between boto3 and mountpoint-s3. Maybe there's some changes to the environment influencing the AWS credentials used by the subprocess - mountpoint-s3 logs may help make this clearer.

If no `-l` argument is provided, mountpoint-s3 will already write its logs to syslog - no need to configure that explicitly.

Rather than `-l /var/log/syslog`, can you use something like `-l ~/mountpoint-s3-logs/`? This will ensure mountpoint-s3's logs are written to a directory in your home directory. These logs should tell you what's happening with any errors, and if using `--debug` then you should learn more about what the file system is doing. It would be great if you can share those logs here to help identify the issue.

**Comment by dannycjones** [comment]
I suspect you're running inside Docker? Instead of `-l ~/mountpoint-s3-logs`, go ahead and choose something that will be accessible to you outside the container. You may want to bind a directory just for these logs if its easier.

For example, if running using docker run:

```
docker run -v ~/mountpoint-s3-logs:/mountpoint-s3-logs ...
```

And then use the argument `-l /mountpoint-s3-logs` with mountpoint-s3.

**Comment by juanmarti81** [comment]
Sorry for the late response. I've managed to get the logs. Some inputs to clarify:
I'm mounting 2 buckets: input_bucket (gjl-safebox) and output_bucket (c-stt)

```
os.makedirs("/mnt/" + output_bucket, mode=777, exist_ok=True)
subprocess.run(
    ["mount-s3", "--allow-delete", "--allow-other", "--dir-mode", "777", 
     "--debug", output_bucket, "/mnt/" + output_bucket, "-l", "/var/log/syslog"],
    check=True
    )

os.makedirs("/mnt/" + input_bucket, mode=777, exist_ok=True)
subprocess.run(
    ["mount-s3", "--allow-delete", "--allow-other", "--dir-mode", "777", 
     "--debug", input_bucket, "/mnt/" + input_bucket, "-l", "/var/log/syslog"],
    check=True
    )
```

Some the errors i've found:
```
2023-09-22T22:38:50.826995Z DEBUG lookup{req=4 ino=1 name="Mezz_038783_UNI_Strays2023_TR_HD_VLAS_STT.mp4"}:head_object{id=3 bucket="c-stt" key="Mezz_038783_UNI_Strays2023_TR_HD_VLAS_STT.mp4"}: mountpoint_s3_client::s3_crt_client: failed meta request result: MetaRequestResult { response_status: 404, crt_error: Error(14343, "aws-c-s3: AWS_ERROR_S3_INVALID_RESPONSE_STATUS, Invalid response status from request"), error_response_headers: Some(Headers { inner: 0x7faae004ce10 }), error_response_body: None }
```
```
2023-09-22T22:39:18.199578Z  WARN open{req=7 ino=2}:put_object{id=9 bucket="c-stt" key="Mezz_038783_UNI_Strays2023_TR_HD_VLAS_STT.mp4"}: mountpoint_s3_client::s3_crt_client: meta request failed duration=27.309595366s error=ClientError(CrtError(Error(1063, "aws-c-io: AWS_IO_STREAM_READ_FAILED, Stream failed to read from the underlying io source")))
```

Attached is full log file.
[mountpoint-s3-2023-09-22T22-38-49Z.log](https://github.com/awslabs/mountpoint-s3/files/12705012/mountpoint-s3-2023-09-22T22-38-49Z.log)

**Comment by dannycjones** [comment]
Hey Juan,

This is the error causing the problem:

```
2023-09-22T22:39:18.167360Z  WARN write{req=50 ino=2 fh=1 offset=36 length=4}: mountpoint_s3::fuse: write failed: upload error: out of order write; expected offset 3461864 but got 36
```

Random writing to files is not supported by mountpoint-s3. As part of #533, we are reviewing what changes we can make to better surface these errors.

Assuming `Mezz_038783_UNI_Strays2023_TR_HD_VLAS_STT.mp4` is your output file, it appears that ffmpeg is performing random writes on this particular workload. Is there any way your ffmpeg workload can be configured to not require random write access to the files?

**Comment by juanmarti81** [comment]
Thanks Danny for the explanations. I don't know if there's a possibility to do that but I will investigate and drop a comment if I find a solution.

**Comment by dannycjones** [comment]
Closing this for now. Non-sequential writing to files is not supported by mountpoint-s3 today.
