### ISSUE TITLE
Support providing SSE-KMS key ID for all new files

### ISSUE THREAD

**Issue by meetreks** [awslabs/mountpoint-s3#534]
### Tell us more about this new feature.

mountpoint-s3 should support passing of the KMS key ID for SSE-KMS, similar how it can be provided for other S3 clients like the SDKs. This will help with customers who insist that any S3 _PutObject_ is required to explicitly specify a known key ARN as part of their S3 Bucket Policy. The policy is a standard policy and recommended best practices.

**Comment by dannycjones** [comment]
Hey @meetreks, thanks for opening this feature request.

I think this is an ask specifically related to SSE-KMS (rather than another encryption mode), so I've updated the title accordingly. I also clarified that it would be for all new files, rather than a per-file configuration/option. Please correct me if I've assumed wrong!

**Comment by manokaran3529** [comment]
Would be a great and must have feature!
Late to the party but surprised to see this isn’t supported yet. It will be a lot helpful if this gets prioritised please.

**Comment by justinas-b** [comment]
Hey! We also use below S3 bucket policies to enforce encryption, which prevents from having write access to volume

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DenyIncorrectEncryptionHeader",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::mybucket/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": "AES256"
                }
            }
        },
        {
            "Sid": "DenyUnEncryptedObjectUploads",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::mybucket/*",
            "Condition": {
                "Null": { 
                    "s3:x-amz-server-side-encryption": "true"
                }
            }
        }
    ]
}
```

I see linked pull requests that are merged, @vladem any ideas when we could expect this feature to be available?

**Comment by vladem** [comment]
Hey @justinas-b, thanks for sharing your use-case! We are working on this issue, but unfortunately, I am not able to share any dates just yet. The policy, that you've attached requires slight adjustments to the implementation, that we're working on. We've created a separate issue to track this enhancement: https://github.com/awslabs/mountpoint-s3/issues/807

**Comment by dannycjones** [comment]
We launched this feature in v1.6.0! https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-1.6.0
