### ISSUE TITLE
Add mode to handle tar files as webdataset

### ISSUE THREAD

**Issue by tchaton** [awslabs/mountpoint-s3#540]
### Tell us more about this new feature.

Hey there,

I was studying Web Dataset internals and it stream tar sub files to the use code.

I was thinking it could be possible to have a mode where MountPoint S3 could list tar files on s3 and exposes them as un-tarred to the file system through the mount.

When reading a given file, it would read the entire tar locally. Obviously, the user would need to read files in the order of the tar files to gain maximum speed from this mode.

But this would provide a simple and very efficient way to stream data to the machine.

Best,
T.C

**Comment by monthonk** [comment]
Hey, thanks for opening this feature request. It is really an interesting use case and we will be looking into it.

By the way, I think if your use cases are read-only. It might be worth trying S3 Object Lambda. With S3 Object Lambda you can replace LIST, GET, and HEAD requests of tar files with untarred contents. Then you can use the Object Lambda access point on mounting and it should work without having to make any changes in Mountpoint.

**Comment by tchaton** [comment]
Hey @monthonk Do you have an example on how to do that ?

**Comment by monthonk** [comment]
Sorry, I don't have any example in my hands. The [S3 Object Lambda documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transforming-objects.html) might have some examples for you.

I don't know much about Web Dataset, but want to clarify something. Does it currently work with tar files in Mountpoint? I'm assuming that it works, but Web Dataset would sequentially read the entire tar file. What you want here is an optimization which let you know what to look at in the tar file and only download the part you want from the object. Is that correct?

**Comment by tchaton** [comment]
Hey @monthonk. After checking AWS Lambda, this doesn't seem like a good option. I assume this would make it too slow to be usable. 

I meant to have something built directly within the fuse mount.

**Comment by jamesbornholt** [comment]
We've looked into this a little, and while I think it would be pretty cool, it's not something we're currently planning on implementing for Mountpoint. It's worth noting that applications loading WebDataset-format objects (tar files) from a Mountpoint instance works today, including being able to seek through the tar file when needed to skip over files. What doesn't exist is the ability for Mountpoint to "mount" a tar file and present its contents as individual files.

Thanks for the feedback!
