### ISSUE TITLE
Introduce a python async reading for files

### ISSUE THREAD

**Issue by tchaton** [awslabs/mountpoint-s3#544]
### Tell us more about this new feature.

As expected using aiofiles to read from mountpoints3 provides a pretty good speed up. 

```python
from time import time
import os
from tqdm import tqdm
import asyncio
import aiofiles

folder = "imagenet/train/n02837789"

paths = [os.path.join(folder, f) for f in os.listdir(folder)]

t0 = time()
for path in tqdm(paths, total=len(paths)):
    with open(path, "rb") as f:
        data = f.read()
print(time() - t0)
# out: 398.5219008922577


t0 = time()
async def read_file(path):
    async with aiofiles.open(path, mode='rb') as f:
        contents = await f.read()

coros = []
for path in paths:
    coros.append(read_file(path))
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
results = loop.run_until_complete(asyncio.gather(*coros))
print(time() - t0)
# out: 67.671071767807
```

I believe it could be possible to get even faster with a custom aofiles library that supports multi part download over the await f.read()

```python
from mountpoints3 import aiofiles

async def read_file(path):
    async with aiofiles.open(path, mode='rb') as f:
        contents = await f.read(part_size=1 << 22) # trigger multi part download and store the data into an ordered buffer while flushing to python
```

**Comment by dannycjones** [comment]
Hey @tchaton, what's the challenge we want to solve with this feature? Are we trying to maximize single file throughput by opening a file multiple times?

Instead, can this issue be solved by parallelizing reads over multiple files (so long as the workload plans to process the files concurrently)?

**Comment by jamesbornholt** [comment]
Internally, Mountpoint is already triggering a multi-part download when you call `await f.read()`. It won't matter in this case because imagenet images are so small that one request per file is the right answer, but for larger files, Mountpoint will use a prefetcher and will automate the multi-part download for you already.

**Comment by tchaton** [comment]
Hey @dannycjones @jamesbornholt, you are right. The challenge I am trying to solve is the slowness from reading from a s3 mount using synchronous code. However, this is something I can enforce on my side. So nothing to be added on your end.
