### ISSUE TITLE
mount-s3 --no-log flag still sends log to the console

### ISSUE THREAD

**Issue by miguelmachacon** [awslabs/mountpoint-s3#550]
### Mountpoint for Amazon S3 version

mount-s3 1.0.2

### AWS Region

eu-central-1

### Describe the running environment

Running in Amazon EC2 with Amazon Linux 2023 connected to the same S3 account. 

![Screenshot 2023-10-10 at 16 30 14](https://github.com/awslabs/mountpoint-s3/assets/147605870/1f55da83-6bec-4ca5-8c1e-fbdd84f84f5d)

### What happened?

I tried to mount the s3 without any log and 'bucket incomingmedia-migchag is mounted at /media/s3' appeared in the console even if launched it with --no-log flag enabled

### Relevant log output

```shell
'bucket incomingmedia-migchag is mounted at /media/s3'
```

**Comment by arsh** [comment]
Hello @miguelmachacon, did this behavior cause any issues or was it just a surprise?

We intentionally want to print to stdout after a successful mount as a way to provide a feedback to the user and don’t think `--no-log` option should prevent it. To prevent anything being printed to the stdout, redirects can be used. For example 

```
mount-s3 <BUCKET_NAME> ~/mnt 1>/dev/null
```

**Comment by dannycjones** [comment]
Please let us know if there's still an issue here, I'll close this issue for now.
