### ISSUE TITLE
Backup DB2 database to S3 endpoint ERROR 

### ISSUE THREAD

**Issue by picoroma** [awslabs/mountpoint-s3#553]
### Mountpoint for Amazon S3 version

mount-s3 1.0.2

### AWS Region

eu-west-1

### Describe the running environment

EC2 Instance with IBM DB2 10.5 Installed

Mount the S3 endpoint as local FileSystem: OK
Can see object and folder into the S3 Bucket

RUNNING the Backup Command:
db2adm 54> db2 backup database CFP to /BACKUP-S3/PROVA-BACKUP

after 10 minutes I have this error:

SQL2419N  The target disk "/BACKUP-S3/PROVA-BACKUP" has become full.

HOw can be possible?

### What happened?

SQL2419N  The target disk "/BACKUP-S3/PROVA-BACKUP" has become full.

**Comment by dannycjones** [comment]
Hey @picoroma,

Please can you share the full `mount-s3` command you used (bucket name can be redacted if preferred), along with debug logging from mountpoint-s3? You can configure logging here: https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md

**Comment by dannycjones** [comment]
I'll close this issue for now. If you are still experiencing the issue and have more information you can share, please do re-open this issue or create a new one.
