### ISSUE TITLE
Unable to Mount Cross-Account S3 Bucket

### ISSUE THREAD

**Issue by naavveenn** [awslabs/mountpoint-s3#561]
### Mountpoint for Amazon S3 version

mount-s3 1.0.2

### AWS Region

us-west-2

### Describe the running environment

I have an instance in account A, and I need to mount a S3 bucket located in account B. To achieve this, I'm utilizing the `Mountpoint-S3` feature, but I've encountered difficulties in mounting the bucket as it doesn't support cross-account mounting.
The only way I was able to achieve this was by generating temporary tokens using the `aws sts assume-role` command. While this serves as a temporary workaround, it's not a scalable or efficient solution. 

Can we introduce functionality that allows us to directly mount S3 buckets from different AWS accounts without the need for temporary tokens or workarounds?

### What happened?

Anticipating the successful mounting of the cross-account bucket on the EC2 instance.

### Relevant log output

```shell
# mount-s3 s3fs-test-bucket /s3-mount

Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket s3fs-test-bucket in region us-west-2
    1: Client error
    2: Forbidden: Access Denied
Error: Failed to create mount process
```

**Comment by jamesbornholt** [comment]
Mountpoint definitely supports cross-account mounting. The error message you're getting suggests that the credentials Mountpoint is using don't have the access you're expecting them to. Mountpoint uses the same credentials resolution as the AWS CLI, so could you try running `aws s3 ls s3://yourbucketname/` from the same host you're running Mountpoint on? That will help understand if the issue is Mountpoint-specific or not.

**Comment by naavveenn** [comment]
The method didn't yield the desired results for me. The role attached to the EC2 instance grants the following permission: it allows assuming the role in Account B to access the S3 bucket, as outlined below:

```
{
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Resource": [
                "arn:aws:iam::123456789:role/s3-access-role"
            ],
            "Sid": ""
        }
    ],
    "Version": "2012-10-17"
}
```

To make this role functional, I resorted to generating a temporary token using the following commands:

```
aws sts assume-role --role-arn arn:aws:iam::123456789:role/s3-access-role --role-session-name test
export AWS_ACCESS_KEY_ID=xxxxxxxx
export AWS_SECRET_ACCESS_KEY=yyyyyyyyy
export AWS_SESSION_TOKEN=xxxxxxxxyyyyyyyyy

With the above access key, secret key, and session token, I successfully listed the Account B bucket and mounted it as follows:

mkdir /test-s3-mount
mount-s3 s3fs-test-bucket /test-s3-mount

echo "testing s3 mounting" > /test-s3-mount/data.txt
ls /test-s3-mount/

```

However, there is an issue with this approach. If the token expires after the default timeout, it disrupts connectivity with the S3 bucket, necessitating the repetition of the above steps for remounting. This process is not a sustainable solution.

**Comment by jamesbornholt** [comment]
If the EC2 instance profile has permission to assume the role, you can configure Mountpoint (and the CLI) to automatically assume it for you (and it will manage refreshing the credentials): https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html

Something like this in your `~/.aws/config`:
```
[profile somenamehere]
role_arn = arn:aws:iam::123456789:role/s3-access-role
credential_source = Ec2InstanceMetadata
```
then run Mountpoint with `--profile somenamehere`.

**Comment by naavveenn** [comment]
Thanks! I successfully mounted the cross-account bucket using the method you recommended. However, we've encountered a couple of issues:
i) Creating a folder inside a bucket that's mounted on an EC2 instance directly from the instance is not possible.
ii) Even with the appropriate permissions to delete objects, we are unable to delete a file from the EC2 instance.

Is this a limitation, or could I be overlooking something?

**Comment by jamesbornholt** [comment]
> i) Creating a folder inside a bucket that's mounted on an EC2 instance directly from the instance is not possible.

Do you mean that `mkdir` returns an error, or something else? The expected behavior is that a new directory won't be uploaded to S3 until it has an object inside it: https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#modifying-directories

>  ii) Even with the appropriate permissions to delete objects, we are unable to delete a file from the EC2 instance.

You probably need to pass the `--allow-delete` flag to Mountpoint; deletes are disabled by default (https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#reading-and-writing-files).

**Comment by naavveenn** [comment]
thanks a lot, I've tested both scenarios and it's working fine. Just a final question, is there a way we can see which bucket is mounted on which directory? Something like `df -h` command.

**Comment by jamesbornholt** [comment]
No, not currently — `df` doesn't give us enough flexibility to include a bucket name.
