### ISSUE TITLE
How do eks Pods mount S3 through stroageclass?

### ISSUE THREAD

**Issue by Jerrywgl** [awslabs/mountpoint-s3#563]
### Tell us more about this new feature.

How do eks Pods mount S3 through stroageclass?

**Comment by jamesbornholt** [comment]
The way to do this is using a CSI driver, which doesn't currently exist for Mountpoint. You can track our progress on that here, and/or upvote it if it's important to your use case: https://github.com/awslabs/mountpoint-s3/issues/150
