### ISSUE TITLE
"http_status=503" When downloading with high concurrency

### ISSUE THREAD

**Issue by likewtf1** [awslabs/mountpoint-s3#574]
I want to use mountpoint-s3 for 100 ec2 machines, which each machine runs as many programs as the number of cpus , to access some files in S3 at the same time. Sometimes it works fine, but sometimes i meet the warning message below:
```
Oct 24 10:58:39 ip-172-31-135-62 mount-s3[453]: [WARN] lookup{req=20094 ino=109 name="***"}:list_objects{id=16589 bucket=*** continued=false delimiter=/ max_keys=1 prefix=***}: mountpoint_s3_client::s3_crt_client: request failed request_type=Default http_status=503 range=None duration=426.995805ms ttfb=Some(7.681499ms) request_id=***
Oct 24 10:58:40 ip-172-31-135-62 mount-s3[453]: [WARN] open{req=20158 ino=1706 pid=1759}:list_objects{id=16643 bucket=*** continued=false delimiter=/ max_keys=1 prefix=***}: mountpoint_s3_client::s3_crt_client: request failed request_type=Default http_status=503 range=None duration=314.021865ms ttfb=Some(8.180981ms) request_id=***
```

I have three questions regarding this:
1. Is this warning report fine? Or how to avoid this? My current structure is like "<bucket>/<date>/files.dat" where there are almost 5000 files in one date. And my program will read 10 days of data simultaneously.
2. Each program will be run 5 hours. During program running ,i find that the memory usage of mount-s3  is steady increasing to almost the whole memory, is it right?
3. In the Cost Explore, i find 'ListBucket' API cost five times than 'GetObject' API. Is that correctly? Or how to reduce the cost?

**Comment by sauraank** [comment]
1. 503 response is there when server side is not able to service your request. But, this is not expected to happen frequently.
2. We may expect it to grow if there's a lot of concurrent file operations, but it should also be deallocating the memory too. You may share the logs so that we can take a look at the metrics to know if there is any memory leak.

**Comment by sauraank** [comment]
3. While using Mountpoint, there are higher number of List bucket requests because it is made everytime we have to `Lookup` for a file/directory. We are working on reduce the cost on repeated access. You can track it here: https://github.com/awslabs/mountpoint-s3/issues/255.

**Comment by likewtf1** [comment]
Thanks! I am going to tar my files and change the structure in s3 to avoid 503 warning. I will update this issue when finished test.

**Comment by dannycjones** [comment]
I hope the issue was resolved! Please do re-open the issue or open a new issue if you are encountering problems.
