### ISSUE TITLE
Docs: Configuring link dead

### ISSUE THREAD

**Issue by BioTurboNick** [awslabs/mountpoint-s3#578]
On the readme, there's a callout link to "[Configuring Mountpoint for Amazon S3](https://github.com/awslabs/doc/CONFIGURATION.md)", but the document doesn't exist. GitHub returns a blank page saying "Not Found".

I presume this is the intended URL? https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md

**Comment by passaro** [comment]
That's correct. Same problem with [Installing Mountpoint for Amazon S3](https://github.com/awslabs/doc/INSTALL.md). They are both in "highlight" sections (introduced in #569). I suspect it could be a github markdown rendering issue.
