### ISSUE TITLE
[BUG] `mountpoint_s3::fuse: release failed: unable to unwrap file handle reference`

### ISSUE THREAD

**Issue by BobDu** [awslabs/mountpoint-s3#582]
### Mountpoint for Amazon S3 version

1.0.2

### AWS Region

cn-north-1

### Describe the running environment

os:
```
ubuntu@ip-x-x-x-x:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### What happened?

Can not upload file to s3.
<img width="1594" alt="image" src="https://github.com/awslabs/mountpoint-s3/assets/20370175/5b87a72e-b7de-4e39-a8a7-0efd283bb0b1">

### Relevant log output

```shell
[WARN] release{req=70306 ino=865 fh=4558}: mountpoint_s3::fuse: release failed: unable to unwrap file handle reference
```

**Comment by dannycjones** [comment]
Hey @BobDu, we're going to need more information than this to understand what went wrong.

Are you able to provide more details logging with `--debug`? I also recommend configuring logs to be written to a file using the `--log-directory` argument. More details in this document: https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md

Can you also tell us a bit about what application is running using the file system? Who is creating the new files / uploads?

**Comment by dannycjones** [comment]
I'll close this issue for now. Please do re-open the issue if you are still encountering this and have additional information.

**Comment by djhenry2** [comment]
I have had the same problem.

I set up logging as recommended with --debug and --log-directory.

The resulting log file is attached.
[mountpoint-s3-2023-12-07T13-52-09Z.log](https://github.com/awslabs/mountpoint-s3/files/13601607/mountpoint-s3-2023-12-07T13-52-09Z.log)
