### ISSUE TITLE
DOCS: How to make mount permanent

### ISSUE THREAD

**Issue by ixodie** [awslabs/mountpoint-s3#583]
### Tell us more about this new feature.

I would like to know how to permanently mount the S3 bucket, so that when the linux server is rebooted the mount is persisted.

Can anyone provide a recommendation for how to do it?

**Comment by sauraank** [comment]
Hi @ixodie ! One of the workaround you may try is automount your bucket on your instance reboot by using systemd. You can track how to do it from #441 . 
We also have a feature request open for Compatibility with fstab #44 which supports mounting a folder to a bucket after reboot. Please do thumbs up if that's important for you. Thanks.

**Comment by dannycjones** [comment]
Thanks for the documentation update request. I think we should add a note for this, even if we don't have the perfect solution yet. I'll leave this open until we have documentation updated for this.
