### ISSUE TITLE
Fargate support

### ISSUE THREAD

**Issue by kalupad** [awslabs/mountpoint-s3#586]
### Tell us more about this new feature.

At present, mountpoint-s3 cannot be used with the Fargate runtime because it doesn't support privileged mode. There have been numerous discussions on s3-fargate integration over the past few years without any tangible efforts. Implementing this feature would greatly benefit many existing AWS customers. Are you planning to work on it?

**Comment by dannycjones** [comment]
Thanks for the feature request, Damian! I can definitely see the benefits of this integration.

I don't have anything to share on Fargate support right now. We are tracking interest for Fargate support in #450. I will close this issue in favor of that one.
