### ISSUE TITLE
Mountpoint maximum throughput limit and not scaling up with increase resources.

### ISSUE THREAD

**Issue by scottma** [awslabs/mountpoint-s3#636]
### Mountpoint for Amazon S3 version

mount-s3.1.2.0

### AWS Region

us-east-1

### Describe the running environment

AWS Parallel Cluster 3.7.1, OS AL2, single AZ, us-east-1

### Testing tool:
IOR https://github.com/hpc/ior

### mount option:
--allow-delete --allow-root

### tested with the following combination (# of instances x instance type x network throughput)
1x c7i.8xlarge (12.5gbps)
6x c7i.8xlarge 
3x c7i.16xlarge (25gbps)
3x g4dn.8xlarge (50gbps)
1x c6in.16xlarge (100gbps)

### What happened?

regardless how many instances are used, it looks like the maximum throughput is limited to ~ max 4GiB/s (4.3GB/s) for read and write depending on the testing settings (e.g. buffer size, transfer size). We should see some multiple of throughput increase if multiple instances are added to the test. It is particularly an issue if it cannot scale up.

The tests are conducted using IOR. A sbatch command is submitted to each node to run IOR. The result is aggregated in the first node. 

Tested with s3 mountpoint and it is limited at 4.3GB/s. 
Tested with EBS and it scaled with the increase number of nodes. 
Tested with max-thread option and it did not change the throughput. 
Tested with reduced number of threads (e.g 8) vs vcpu (e.g. 16 or 32) and it did not change the throughput.

### Relevant log output

```shell
#sbatch submission command
#!/bin/bash
#SBATCH --job-name=ior-perf-test
#SBATCH --output=%N_%x_%j_%t.out
#SBATCH --ntasks=16
#SBATCH --ntasks-per-node=8
export I_MPI_PIN_RESPECT_CPUSET=0
export I_MPI_HYDRA_BOOTSTRAP=slurm
module load intelmpi
mpirun bash "ior -r -w -v -F -o=\<dir> -b=640m -a=POSIX -i=1 -t=64m"
```

**Comment by scottma** [comment]
yes, I have tried that --maximum-throughput-gbps 50 & 100 and --max-threads 32 (for 16xlarge). The strange thing is it does not seem to make a bit of a difference.  I also looked at the ec2 monitoring for network in and out, it max out at ~8-9gbps. I tried c6in.16xl with 100gbps throughput, it max out like in a c6i.8xlarge. 

so, it is not maxing out the actual ec2 network throughput and vcpus ...etc. I wonder if there is some config that is limiting the throughput (e.g. max_concurrent_requests).

**Comment by sauraank** [comment]
It might also due to limit reached on service side for S3. Can you please check if you are getting 503(Slow Down) error. In that you might need to redistribute your object into more keys.

**Comment by dannycjones** [comment]
> It might also due to limit reached on service side for S3. Can you please check if you are getting 503(Slow Down) error? In that you might need to redistribute your object into more prefix. You can check https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html.

Just to add a bit of information, you can use the `--log-metrics` flag to output metrics about things like HTTP 503 counts from S3 requests when using Mountpoint. If you are seeing this number appear and trend up, that would help confirm that what you're seeing is high load on a prefix partition.

**Comment by scottma** [comment]
I turned on the log metrics. I can see initially have a few 404 on HeadObject. The lookup (file does not exist) on avx512_1, tls, x86_64..etc seems to repeat every sec or so. I am not requesting those files (I don't have docker installed on this machine.). wondering if it would cause performance issues. highlighted are in question.

Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.num_auto_ranged_get_network_io: 0
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.num_auto_ranged_put_network_io: 0
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.num_requests_being_prepared: 0
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.num_requests_being_processed: 1
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.num_requests_stream_queued_waiting: 0
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.num_requests_streaming_response: 0
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.num_total_network_io: 1
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.client.request_queue_size: 0
**Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.meta_requests.failures[op=head_object,status=404]: 134 (n=134)**
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.meta_requests.first_byte_latency_us[op=head_object]: n=134: min=12928 p10=22015 p50=28671 avg=
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.meta_requests.first_byte_latency_us[op=list_objects]: n=134: min=11968 p10=20223 p50=31103 avg
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.meta_requests.total_latency_us[op=head_object]: n=134: min=12928 p10=22015 p50=28671 avg=28478
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.meta_requests.total_latency_us[op=list_objects]: n=134: min=12032 p10=20223 p50=31103 avg=3245
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.meta_requests[op=head_object]: 134 (n=134)
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.meta_requests[op=list_objects]: 134 (n=134)
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: **s3.requests.failures[op=head_object,type=Default,status=404]: 134 (n=134)
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.requests.first_byte_latency_us[op=head_object,type=Default]: n=134: min=8256 p10=17919 p50=238**
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.requests.first_byte_latency_us[op=list_objects,type=Default]: n=134: min=7648 p10=13247 p50=25
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.requests.total_latency_us[op=head_object,type=Default]: n=134: min=12864 p10=22015 p50=28671 a
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.requests.total_latency_us[op=list_objects,type=Default]: n=134: min=11968 p10=20223 p50=31103
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.requests[op=head_object,type=Default]: 134 (n=134)
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [INFO] mountpoint_s3::metrics: s3.requests[op=list_objects,type=Default]: 134 (n=134)
**Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=846 ino=1 name="haswell"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:49:59 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=848 ino=1 name="avx512_1"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=850 ino=1 name="avx512_1"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=852 ino=1 name="x86_64"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=854 ino=1 name="libtinfo.so.6"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=856 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=858 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=860 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=862 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=864 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=866 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=868 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=870 ino=1 name="tls"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=872 ino=1 name="haswell"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=874 ino=1 name="haswell"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=876 ino=1 name="haswell"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=878 ino=1 name="haswell"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=880 ino=1 name="avx512_1"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=882 ino=1 name="avx512_1"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=884 ino=1 name="x86_64"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=886 ino=1 name="libc.so.6"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
Dec 13 16:50:00 queue1-st-pclustercr1-1 mount-s3[9748]: [WARN] lookup{req=888 ino=1 name="-"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist (edited)**

**Comment by scottma** [comment]
the s3 policy is s3:* for action for those buckets.

**Comment by scottma** [comment]
I've seen improvement, possibly related to new release. I am going to close this.
