### ISSUE TITLE
S3 Express One Zone documentation updates

### ISSUE THREAD

**Issue by dlakhaws** [awslabs/mountpoint-s3#651]
### Tell us more about this new feature.

The [permission recommendation](https://github.com/awslabs/mountpoint-s3/blob/099638eede5fc34756e46b9eb6af6582c8fe1a55/doc/CONFIGURATION.md#iam-permissions) for Mountpoint weren't updated to include [S3 Express One Zone IAM permissions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-express-security-iam-identity-policies.html). Would like to see a section with this added for customers using S3 Express One Zone!

**Comment by jamesbornholt** [comment]
There's a few places in the docs we need to update to include Express One Zone:
* IAM permissions (`s3express:CreateSession`)
* Storage classes (don't use `--storage-class EXPRESS_ONEZONE`, instead just specify a directory bucket)
* Region detection (not sure this works as described for Express)

We should probably also update the semantics documentation to note that `readdir` is unordered on an S3 Express One Zone bucket.
