### ISSUE TITLE
Does not work with AssumeRoleWithWebIdentity (AWS_WEB_IDENTITY_TOKEN_FILE)

### ISSUE THREAD

**Issue by mikkeloscar** [awslabs/mountpoint-s3#675]
### Mountpoint for Amazon S3 version

mount-s3 1.3.1

### AWS Region

eu-central-1

### Describe the running environment

1. Running on custom Ubuntu 22.04 AMI tryoing to connect to a bucket in eu-central-1 via `AssumeRoleWithWebIdentity` credentials

### Mountpoint options

```shell
AWS_WEB_IDENTITY_TOKEN_FILE=/opt/podruntime/kubelet/plugins/s3.csi.aws.com/token AWS_ROLE_ARN="arn:aws:iam::1234:role/my-role-s3-csi-driver" /opt/mountpoint-s3-csi/bin/mount-s3 my-demo-s3-bucket /data --debug-crt --region eu-central-1

Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket my-demo-s3-bucket in region eu-central-1
    1: Client error
    2: Forbidden: Access Denied
Error: Failed to create mount process
```

### What happened?

I'm trying to setup https://github.com/awslabs/mountpoint-s3-csi-driver in a custom Kubernetes on AWS environment. It fails at the stage of running `mount-s3` and I have debugged it down to `mount-s3` seemingly not working when trying to get credentials via: `AssumeRoleWithWebIdentity`.

I run the command:

```
AWS_WEB_IDENTITY_TOKEN_FILE=/opt/podruntime/kubelet/plugins/s3.csi.aws.com/token AWS_ROLE_ARN="arn:aws:iam::1234:role/my-role-s3-csi-driver" /opt/mountpoint-s3-csi/bin/mount-s3 my-demo-s3-bucket /data --debug-crt --region eu-central-1

Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket my-demo-s3-bucket in region eu-central-1
    1: Client error
    2: Forbidden: Access Denied
Error: Failed to create mount process
```

And get the shown error.

I do not think this is a permission problem as I can make the following request with the `aws` cli:

```
AWS_WEB_IDENTITY_TOKEN_FILE=/opt/podruntime/kubelet/plugins/s3.csi.aws.com/token AWS_ROLE_ARN="arn:aws:iam::1234:role/my-role-s3-csi-driver" aws s3 ls
```

Which successfully returns the buckets in the region using the WEB IDENTITY role.

The role has the AWS managed policy `arn:aws:iam::aws:policy/AmazonS3FullAccess` attached.

I found this issue suggesting it should work: https://github.com/awslabs/mountpoint-s3/issues/59 but I can't make it work as shown above.

**Comment by iostreamdoth** [comment]
It might seem like you need to pass env more variables, may be AWS_ROLE_SESSION_NAME, AWS_DEFAULT_REGION
The sts web Identity is part of [aws_credentials_provider_new_chain_default](https://github.com/awslabs/aws-c-auth/blob/main/source/credentials_provider_default_chain.c#L240C34-L240C76) so it should work. May be give that a shot


https://github.com/awslabs/aws-c-auth/blob/main/include/aws/auth/credentials.h#L323
https://github.com/awslabs/aws-c-auth/blob/main/source/credentials_provider_default_chain.c#L348

**Comment by mikkeloscar** [comment]
Thanks a lot for the hint!

Setting `AWS_DEFAULT_REGION=eu-central-1` makes it work. I don't need to set `AWS _ROLE_SESSION_NAME`.

**Comment by sauraank** [comment]
Thanks to let us know it works. Closing this issue for now. If you have any more questions, please re-open this issue or open a new issue.
