### ISSUE TITLE
Fine-grained access control using pod-level IAM permissions

### ISSUE THREAD

**Issue by iamahgoub** [awslabs/mountpoint-s3#680]
### Tell us more about this new feature.

Allow for accessing S3 using pod-level IAM permissions granted through IRSA or recently launched EKS pod identities. Right now, the interaction with S3 is happening through the controller, and the S3 permissions are granted to it rather than the application pod accessing data.

**Comment by dannycjones** [comment]
Hey @iamahgoub, thanks for opening this feature request.

Are you using the [Mountpoint for Amazon S3 Container Storage Interface (CSI) Driver](https://github.com/awslabs/mountpoint-s3-csi-driver/)? It sounds like this is something for the folks who own the CSI Driver to dig into, and you may be better opening the issue over on that repository or we can open it on your behalf. It may still need changes in Mountpoint, but I'm not sure what that might look like right now.

cc @awslabs/aws-s3-csi-driver

**Comment by iamahgoub** [comment]
> Hey @iamahgoub, thanks for opening this feature request.
> 
> Are you using the [Mountpoint for Amazon S3 Container Storage Interface (CSI) Driver](https://github.com/awslabs/mountpoint-s3-csi-driver/)? It sounds like this is something for the folks who own the CSI Driver to dig into, and you may be better opening the issue over on that repository or we can open it on your behalf. It may still need changes in Mountpoint, but I'm not sure what that might look like right now.
> 
> cc @awslabs/aws-s3-csi-driver

Thanks @dannycjones for your reply. Yes, this PFR is for [Mountpoint for Amazon S3 Container Storage Interface (CSI) Driver](https://github.com/awslabs/mountpoint-s3-csi-driver/). I will raise the issue on awslabs/aws-s3-csi-driver.

**Comment by gpicciani** [comment]
PFR opened https://github.com/awslabs/mountpoint-s3-csi-driver/issues/111. We are closing this issue.
