### ISSUE TITLE
it seems that mount-s3 do not support V1 API?

### ISSUE THREAD

**Issue by zhzfight** [awslabs/mountpoint-s3#688]
### Tell us more about this new feature.

it seems that mount-s3 do not support V1 API?

**Comment by dannycjones** [comment]
Hey @zhzfight. Is this feature request regarding the V1 [ListObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html) operation? The S3 documentation recommends to use the ListObjectsV2 API, with the V1 API ListObjects being maintained for backward compatibility. We don't use the V1 ListObjects API in Mountpoint for this reason.

I imagine this ask is coming in relation to third-party S3-like API compatibility - specifically those that may not have implemented the ListObjectsV2 API. [Mountpoint's README captures our thinking well](https://github.com/awslabs/mountpoint-s3/blob/5e41487a27fce641f3f07fbab1dae50ee56ec2d2/README.md#compatibility-with-other-storage-services):

>Mountpoint for Amazon S3 is designed for high-performance access to the Amazon S3 service. While it may be functional against other storage services that use S3-like APIs, we aren't able to provide support for those use cases, and they may inadvertently break when we make changes to better support Amazon S3. We welcome contributions of minor compatibility fixes or performance improvements for these services if the changes can be tested against Amazon S3.

Implementing Mountpoint using the V1 ListObjects API would not be a small change and we would not be comfortable supporting it (maintaining the code, testing it). We won't be adding it any time soon - sorry!

**Comment by zhzfight** [comment]
thanks for reply. i use minio as s3 service. minio support both v2 and v4  S3 API. actually, i can use 'ls' cmd with minio. but i can not create file. i find that mounts3 first POST and then PUT, it is different with goofys, which is only PUT.

**Comment by dannycjones** [comment]
Ah - if its file creation that's failing, I suspect it may be related to a newer feature that Mountpoint uses. For example, we are using additional checksums when uploading objects which launched in 2022. In that particular case, it does look like Minio supports those though: https://github.com/minio/minio/discussions/15723

Sorry I can't be of more help.
