### ISSUE TITLE
Folder becomes inaccessible after deleting a file inside it

### ISSUE THREAD

**Issue by flivieri** [awslabs/mountpoint-s3#701]
### Mountpoint for Amazon S3 version

mount-s3 1.3.2

### AWS Region

us-west-2

### Describe the running environment

EC2 SERVER running SLES 15.2 using an AMI from AWS.

### Mountpoint options

```shell
mount-s3 --allow-delete <BUCKET_NAME> /temp/BackupTemp/ShareMount
```

### What happened?

I'm trying to install the mount-s3.rpm file on SUSE LINUX. 
But, during the RPM installation, I receive a dependency error:

error: Failed dependencies:
        fuse-libs is needed by mount-s3-1.3.2-1.x86_64

The point is: there is no package on SUSE with the name "fuse-libs".
When I search the repositories, there is a package called "libfuse". That is already installed.

<img width="564" alt="Screenshot 2024-01-12 at 11 03 12 AM" src="https://github.com/awslabs/mountpoint-s3/assets/101843117/f66abb89-dd74-46d4-b949-f9671539cb9e">

I tried to install mount-s3 ignoring the dependencies, but it's not working correctly.
I can mount, but I'm getting some errors creating files or accessing folders inside the mount point. Probably because of this dependency.
Is the application compatible with SLES? If not, there are any plans to make it compatible?
Thanks!

**Comment by passaro** [comment]
Hi @flivieri, thanks for raising the issue. Different linux distributions can package things in different ways and the release .rpm may not cover all of them. Workarounds include [manually installing the binary](https://github.com/awslabs/mountpoint-s3/blob/main/doc/INSTALL.md#other-linux-distributions) or [building from source](https://github.com/awslabs/mountpoint-s3/blob/main/doc/INSTALL.md#building-mountpoint-for-amazon-s3-from-source).

In your case, though, it seems that Mountpoint was indeed installed. If you can mount successfully, the missing dependency is *probably* not an issue. 

**Could you provide more details on the errors you are seeing?**

**Comment by flivieri** [comment]
Hello @passaro 
Thanks for the explanation.

I thought my problem was related to the missing dependency.

What is happening: If I create a subfolder and access this new folder, everything is ok.
But, If I create a file inside/folder inside this new folder, and delete them after that, my folder becomes inaccessible. 
Instead of "blank folder", seems like I'm inside a folder that no longer exists. I cannot list, create files, or type "cd .." to go back.

On S3, the folder no longer exists. At the moment I deleted the files inside the folder, the folder is also deleted by S3.
Example:

<img width="718" alt="image" src="https://github.com/awslabs/mountpoint-s3/assets/101843117/eab92a94-6075-4c95-86d1-fd4ce4801497">

<img width="652" alt="Screenshot 2024-01-12 at 3 25 52 PM" src="https://github.com/awslabs/mountpoint-s3/assets/101843117/ad7a6e4c-21bd-4d51-b8e8-75ee001095ed">

After that, I decide to delete the file inside the folder:

<img width="712" alt="Screenshot 2024-01-12 at 3 27 00 PM" src="https://github.com/awslabs/mountpoint-s3/assets/101843117/1409a784-f233-4350-b253-658294838d08">

<img width="874" alt="Screenshot 2024-01-12 at 3 27 27 PM" src="https://github.com/awslabs/mountpoint-s3/assets/101843117/92fd306c-e8e6-487d-94fd-268b7e0a0865">

Is this a normal behavior? 
Thank you.

**Comment by passaro** [comment]
Yes, that is expected. Mountpoint maps key prefixes to directories, but if the last object with a key containing a prefix is deleted, it considers the directory to also have been deleted. From the [Directory Operations](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#directory-operations) section of the file system behavior documentation:

> If Mountpoint later observes that there are no files existing for that directory in S3, Mountpoint will consider the directory to have been deleted.

**Comment by flivieri** [comment]
Hello @passaro 
Sorry for bothering you and thanks for the explanation.
Best,
