### ISSUE TITLE
Installation fails in Sagemaker Classic kernel console

### ISSUE THREAD

**Issue by mandelkow** [awslabs/mountpoint-s3#707]
### Mountpoint for Amazon S3 version

https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.deb

### AWS Region

eu-west-1

### Describe the running environment

Sagemaker Classic image "Datascience 3.0" running on ml.t3.medium.
```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Mountpoint options

```shell
none
```

### What happened?

Installation according to README instructions failed. See output below.
```
# wget https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.deb
--2024-01-19 17:45:50--  https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.deb
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.163.48, 54.231.132.208, 54.231.197.232, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.163.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10919050 (10M) [binary/octet-stream]
Saving to: ‘mount-s3.deb’

mount-s3.deb                               100%[=======================================================================================>]  10.41M  16.8MB/s    in 0.6s    

2024-01-19 17:45:51 (16.8 MB/s) - ‘mount-s3.deb’ saved [10919050/10919050]

# apt-get install -y ./mount-s3.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'mount-s3' instead of './mount-s3.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mount-s3 : Depends: fuse but it is not installable
            Depends: libfuse2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by passaro** [comment]
Hi @mandelkow, this looks like an issue with your package manager. Is that something you can configure on the instance? Have you checked Sagemaker Classic documentation?

**Comment by mandelkow** [comment]
Running `apt-get update` before the installation solved the installation problem.

Alas, `mountpoint-s3 <bucket_name> <mount_point>` still won't work inside a Sagemaker kernel instance.
According to some internet sources the following error is related to running a Docker container with limited permissions.
```
fuse: device not found, try 'modprobe fuse' first
Error: Failed to create FUSE session
 
Caused by:
    No such file or directory (os error 2)
Error: Failed to create mount process
```

**Comment by passaro** [comment]
You are right, in order to use Mountpoint in a container, Docker needs to be configured with `--cap-add SYS_ADMIN --device /dev/fuse` (see docs for more details: https://github.com/awslabs/mountpoint-s3/blob/main/docker/README.md).

Of course, that may not be supported when using a service like Sagemaker.

**Comment by passaro** [comment]
Thanks for updating the issue. I'll close it now as not specific to Mountpoint.
