### ISSUE TITLE
Build is not reproducible

### ISSUE THREAD

**Issue by jchorl** [awslabs/mountpoint-s3#728]
### Tell us more about this new feature.

Hi!

Curious if you have advice here - it appears the build hash is dependent on the directory in which it is built.

Here's a first build:

```
docker run -it --rm -v $(pwd):/work -w /work rust:1.75 bash
root@c908170b63a1:/work# apt-get update && apt-get install -y pkg-config cmake libclang-16-dev libfuse3-dev
root@c908170b63a1:/work# cargo clean
root@c908170b63a1:/work# cargo build --release
root@c908170b63a1:/work# md5sum target/release/mount-s3
20bfe7fca7772f64162f9bae882c1fc9  target/release/mount-s3
```

And another:

```
docker run -it --rm -v $(pwd):/work-other -w /work-other rust:1.75 bash
root@12eca7b760ef:/work-other# apt-get update && apt-get install -y pkg-config cmake libclang-16-dev libfuse3-dev
root@12eca7b760ef:/work-other# cargo clean
root@12eca7b760ef:/work-other# cargo build --release
root@12eca7b760ef:/work-other# md5sum target/release/mount-s3
be58618b5e1fc7b731428ba53f510b00  target/release/mount-s3
```

Notice the mount dirs are different, and likewise the hash is different.

Note that the cause does not seem to be timestamps stamped into the build, as mounting into the same dir produces the same hash. Running `cargo clean` and re-running the first build produces the same hash, `20bfe7fca7772f64162f9bae882c1fc9`.

We also know that it is not hostname related as the containers should have different hostnames.

Running `strings` on the binary shows that the build path actually does show up:
```
root@743bc66f6931:/work# strings target/release/mount-s3 | grep /work/
...
/work/mountpoint-s3-crt-sys/crt/aws-lc/crypto/pem/..
/work/mountpoint-s3-crt-sys/crt/aws-lc/crypto/pem/pem_oth.c
/work/mountpoint-s3-crt-sys/crt/aws-lc/crypto/pem/pem_pkey.c
/work/mountpoint-s3-crt-sys/crt/aws-lc/crypto/pem/pem_xaux.c
/work/mountpoint-s3-crt-sys/crt/aws-lc/crypto/pkcs7/pkcs7_x509.c
/work/mountpoint-s3-crt-sys/crt/aws-lc/crypto/pkcs7
```

Running `strip` on the binary does not help:

```
root@743bc66f6931:/work# strip -o mount-s3.stripped target/release/mount-s3
root@743bc66f6931:/work# strings mount-s3.stripped | grep /work/
...
Error encountered in /work/mountpoint-s3-crt-sys/crt/s2n-tls/crypto/s2n_composite_cipher_aes_sha.c:232
Error encountered in /work/mountpoint-s3-crt-sys/crt/s2n-tls/crypto/s2n_composite_cipher_aes_sha.c:242
Error encountered in /work/mountpoint-s3-crt-sys/crt/s2n-tls/crypto/s2n_composite_cipher_aes_sha.c:252
Error encountered in /work/mountpoint-s3-crt-sys/crt/s2n-tls/crypto/s2n_composite_cipher_aes_sha.c:262
Error encountered in /work/mountpoint-s3-crt-sys/crt/s2n-tls/crypto/s2n_composite_cipher_aes_sha.c:272
```

Using `objdump`, we can see some of the paths appear in `rodata`. I suspect it has to do with the CRT and cmake.

I tried messing around with [`BUILD_RPATH_USE_ORIGIN`](https://cmake.org/cmake/help/latest/prop_tgt/BUILD_RPATH_USE_ORIGIN.html) and changing the build profile to no avail.

Anyway, I'm not sure if this is at all a priority or of interest. Many build systems rely on reproducibility for caching. I suspect we're not far off here, and with a few flags, we might be able to achieve it. However I'm about at the end of my line in terms of debugging.

Let me know if you have ideas! Feel free to close if this is not important to the project. I can hack around it for now.

**Comment by jamesbornholt** [comment]
Yeah, it looks like this is mostly the CRT's error handling macros just using `__FILE__` directly ([s2n](https://github.com/aws/s2n-tls/blob/6c7cdc8329d846d7fcc8e505cd7708e3f2604d70/error/s2n_errno.h#L351) and [aws-c-common](https://github.com/awslabs/aws-c-common/blob/901405ec8c54da3a773e9699de1cbb43730267f3/include/aws/common/assert.h#L85-L90)). Those are probably pretty easy to change, but from a quick glance at `strings` there's a bit of a long tail of other stuff including from a variety of Rust crates. I think it's probably unlikely we're going to work on this, unfortunately.
