### ISSUE TITLE
Unable to mount non-aws storage due to "Host name was invalid for dns resolution"

### ISSUE THREAD

**Issue by vroni** [awslabs/mountpoint-s3#754]
### Mountpoint for Amazon S3 version

mount-s3 1.4.0

### AWS Region

on-premise

### Describe the running environment

I want to mount a non AWS storage bucket hosted in the same network. I know that you do not offer support for 3rd party storage providers but this seems like a user error on my side. I feel like I am missing something to get it working.

### Mountpoint options

```shell
mount-s3 --profile my-profile --endpoint-url "https://my.s3-storage-url.com" my-bucket /mount_s3/
```

### What happened?

Mount fails using profile and endpoint url information:
`mount-s3 --profile my-profile --endpoint-url "https://my.s3-storage-url.com" my-bucket /mount_s3/`
Using the same parameters works to verify the bucket location when using the aws cli:
`aws s3 ls s3://my-bucket --profile my-profile --endpoint-url "https://my.s3-storage-url.com"`

### Relevant log output

```shell
Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket my-bucket in region us-east-1
    1: Client error
    2: Unknown CRT error
    3: CRT error 1059: aws-c-io: AWS_IO_DNS_INVALID_NAME, Host name was invalid for dns resolution.
Error: Failed to create mount process
```

**Comment by jamesbornholt** [comment]
You might need to use `--force-path-style` if your storage provider doesn't support [virtual-hosted-style buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html).

**Comment by vroni** [comment]
That actually did the trick, thank you so much for the help!
