### ISSUE TITLE
Clarify the expected behavior of the `--metadata-ttl` option set to zero

### ISSUE THREAD

**Issue by mhnap** [awslabs/mountpoint-s3#759]
In an attempt to disable the metadata cache, I set the `--metadata-ttl=0`, referencing https://github.com/awslabs/mountpoint-s3/pull/616 as a potential guide. However, this resulted in a significant increase in `List` and `Head` requests, exceeding even the number observed with the cache completely disabled.

While I'm uncertain about the intended behavior of `--metadata-ttl=0`, I assume it should either disable the metadata cache (if feasible) or be prevented from being accepted as a CLI option.

**Comment by jamesbornholt** [comment]
Yes, `--metadata-ttl=0` disables metadata caching entirely, which is almost certainly not a good thing, as filesystem performance with zero metadata caching is very bad. For Mountpoint, that means sending many more LIST/HEAD requests than necessary, as you're seeing.

When caching is disabled (i.e. no `--cache` or `--metadata-ttl` is set), the actual setting is roughly the same as `--metadata-ttl=0.1` (noting that you can't actually set that as a float), as this comment explains:

https://github.com/awslabs/mountpoint-s3/blob/022f915f76535e517175a8e11291eedaeec92932/mountpoint-s3/src/fs.rs#L303-L313

This `0.1` setting is also the reason our documentation has a [caveat around consistency](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#consistency-and-concurrency):

> However, Mountpoint may return stale metadata for an existing object within 1 second of the object being modified or deleted in your S3 bucket by another client. This occurs only if the object was accessed through Mountpoint immediately before being modified or deleted in your S3 bucket. The stale metadata will only be visible through metadata operations such as stat on individual files. Directory listings will never be stale and always reflect the current metadata. These cases do not apply to newly created objects, which are always immediately visible through Mountpoint. Stale metadata can be refreshed by either opening the file or listing its parent directory.

We probably should just forbid `--metadata-ttl=0`, or convert it to mean the same thing as the default value, as I can't imagine a setting where it would actually work well. Until then, I think `--metadata-ttl=1` is likely the effect you're looking for.

**Comment by mhnap** [comment]
@jamesbornholt Thank you for such a detailed explanation. Now it's clear to me why I saw such behavior for the `--metadata-ttl=0` case. I just didn't realize that `--metadata-ttl=0` would result in different settings than disabled caching.

Now, as I understand that `--metadata-ttl=0` is technically valid and produces expected behavior, the only proposition I have is to add more details about the current default TTLs settings to the documentation. Not sure whether any changes are needed on the CLI side.

**Comment by passaro** [comment]
#855 introduces a warning when using `--metadata-ttl=0`:

> [!WARNING] 
> The --metadata-ttl 0 setting is no longer supported and will be removed in a future release. The new --metadata-ttl minimal has a similar effect, but behaves better when latency for S3 requests is high.

We have also added more details in the documentation, see the [Metadata Cache section in CONFIGURATION.md](https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#metadata-cache).
