### ISSUE TITLE
Support for BottlerocketOS

### ISSUE THREAD

**Issue by sumeet-zuora** [awslabs/mountpoint-s3#769]
### Tell us more about this new feature.

When I'm trying to mount S3 bucket to a pod running on Bottlerocket OS worker node, mount failed and the error on pod events said:

```
MountVolume.SetUp failed for volume "<Redacted>" : rpc error: code = Internal desc = Could not mount "<Redacted>" at "/var/lib/kubelet/pods/<Redacted>/volumes/kubernetes.io~csi/<Redacted>/mount": Mount failed: Failed to start systemd unit on host: SELinux policy denies access: Permission denied output:
```

as per https://github.com/awslabs/mountpoint-s3-csi-driver/issues/86 .. it needs to rewrite something on S3 mount side

**Comment by jamesbornholt** [comment]
Thanks for the report! We're aware of the feature request for Bottlerocket support, and we're going to continue tracking it in the CSI driver repository at https://github.com/awslabs/mountpoint-s3-csi-driver/issues/86. I'm going to close this bug just to avoid spreading comments across two issues.
