### ISSUE TITLE
error in issue template

### ISSUE THREAD

**Issue by wumpus** [awslabs/mountpoint-s3#771]
### Mountpoint for Amazon S3 version

current

### AWS Region

github

### Describe the running environment

code error

### Mountpoint options

```shell
code error
```

### What happened?

this line in the ISSUE_TEMPLATE/bug-report.yml does not work:

`        * Have you checked if the issue/error you are facing is mentioned in our [troubleshooting documentation](../../doc/TROUBLESHOOTING.md)?`

When I click on it while filing an issue, it send me to `https://github.com/awslabs/doc/TROUBLESHOOTING.md`, which does not exist. It's one directory too high.

**Comment by jamesbornholt** [comment]
Thanks! It looks like a couple of these links were broken. #772 will fix it.
