### ISSUE TITLE
Support for unlink/rm

### ISSUE THREAD

**Issue by dannycjones** [awslabs/mountpoint-s3#78]
>Deleting objects with Mountpoint for Amazon S3

- [x] #83
- [x] Implement unlink in the filesystem

**Comment by dannycjones** [comment]
My thinking here is to break down the FS changes into two steps:

- Implement link counting to the Inode in one PR, such that we are confident in the changes to operations such as `mknod`, `open`, `release`. 
- Implement `unlink` and the deletion of the object in S3 (by both `unlink` and `release`) in a second PR, after we are confident in the link counting changes.

**Comment by dannycjones** [comment]
Revised break down:

My thinking here is to break down the FS changes into two steps:

- Implement `unlink` and the deletion of the object in S3 in one PR, and open file handles will return IO error if trying to continue to read the deleted file (simple case)
- Implement link counting to the Inode in a follow-up PR, if we feel that open file handles need to be able to continue reading. (more POSIX compliant, although adds complexity around when the delete is performed)

**Comment by jamesbornholt** [comment]
We can't just drop the inode on the floor in response to an `unlink`, as the kernel expects the inode to still exist until the lookup count for the inode reaches zero (via `forget` calls). So it might be easier to do those two things the other way around.

**Comment by jamesbornholt** [comment]
Done in #232.
