### ISSUE TITLE
Support providing `AES256` SSE type with each PutObject request

### ISSUE THREAD

**Issue by vladem** [awslabs/mountpoint-s3#807]
### Tell us more about this new feature.

[The current implementation](https://github.com/awslabs/mountpoint-s3/blob/74df3e2e00c4a7c567832a40287830ee81fe2d26/mountpoint-s3/src/cli.rs#L279) of SSE settings (which is currently hidden behind a compile-time feature flag) only allows specifying `aws:kms`, `aws:kms:dsse` as the possible options to pass to S3 servers. 

There are cases when it's desired to pass `AES256` sse-type instead, e.g. with the policy provided in the [comment](https://github.com/awslabs/mountpoint-s3/issues/534#issuecomment-1961818855):
```
{
    "Sid": "...",
    "Effect": "Deny",
    "Principal": "*",
    "Action": "s3:PutObject",
    "Resource": "...",
    "Condition": {
        "StringNotEquals": {
            "s3:x-amz-server-side-encryption": "AES256"
        }
    }
}
```

**Comment by dannycjones** [comment]
This was released in v1.6.0! https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-1.6.0

Merged in #827.
