### ISSUE TITLE
Error splicing file: File too large 

### ISSUE THREAD

**Issue by maestro7879** [awslabs/mountpoint-s3#816]
### Mountpoint for Amazon S3 version

mount-s3 1.5.0

### AWS Region

us-east-1

### Describe the running environment

AL2 EC2. Copying a 100GB file to the mounted S3 bucket.

### Mountpoint options

```shell
mount-s3 bucket ~/mnt --allow-delete --allow-overwrite
```

### What happened?

Receive this error in the OS - Error splicing file: File too large

**Comment by monthonk** [comment]
Hey @maestro7879, the default maximum object size you can write with mountpoint is about 80GiB. You may need to use bigger part size for your uploads. Please see https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#maximum-object-size for more details.
