### ISSUE TITLE
`ls` fails every second run | `rewinddir` support

### ISSUE THREAD

**Issue by luiscape** [awslabs/mountpoint-s3#819]
### Mountpoint for Amazon S3 version

1.5.0

### AWS Region

us-east-1

### Describe the running environment

EC2 instance (`m6id.2xlarge`) running Ubuntu 20.04.6 LTS.

### Mountpoint options

```shell
mount-s3 --user-agent-prefix "my-agent" --allow-other --log-metrics --debug --cache /tmp/cache/ --metadata-ttl 5 my-bucket /my-mount
```

### What happened?

Calling `ls /my-mount` one time correctly returns the listed files. Calling it a second time fails with:

```
ls: reading directory '/my-mount/': Invalid argument
```

Debug logs show a FUSE error. 

Calling `ls` in any other nested directory doesn't show this error. 

### Relevant log output

```shell
Mar 18 19:58:20 ip-10-1-0-87 mount-s3[1638219]: [DEBUG] fuser::request: FUSE( 36) ino 0x0000000000000001 GETATTR
Mar 18 19:58:20 ip-10-1-0-87 mount-s3[1638219]: [DEBUG] fuser::request: FUSE( 38) ino 0x0000000000000001 READDIRPLUS fh FileHandle(4), offset 0, size 4096
Mar 18 19:58:20 ip-10-1-0-87 mount-s3[1638219]: [WARN] readdirplus{req=38 ino=1 fh=4 offset=0}: mountpoint_s3::fuse: readdirplus failed: out-of-order readdir, expected=166, actual=0
```

**Comment by arsh** [comment]
Hello @luiscape, thanks for reporting this. I was unable to reproduce this issue. Can you provide the full log file?

Thanks!

**Comment by luiscape** [comment]
@arsh I missed a clarification. We run `mount-s3` on the host but expose the mount as a bind mount inside a container (aka "sandbox") in gVisor. gVisor will reuse and rewind dir handles. Maybe mountdir isn't handling `rewinddir` correctly?

I am able to reproduce the issue on the issue with the following C++ program (`listdir.cpp`):

```cpp
#include <stdio.h>
#include <dirent.h>

int main () {
  DIR *dh = opendir("/my-mount");
  if (dh == NULL) {
    printf("failed to open dir\n");
    return -1;
  }

  struct dirent *dirent;
  while ((dirent = readdir(dh)) != NULL) {
    printf("%s\n", dirent->d_name);
  }
  
  printf("rewinding\n");
  rewinddir(dh);
  
  while ((dirent = readdir(dh)) != NULL) {
    printf("%s\n", dirent->d_name);
  }
  
  closedir(dh);
  return 0;
}
```

Compiling and running
```shell
$ g++ -o listdir listdir.cpp && ./listdir
```
will reproduce the issue:

```
2024-03-19T21:00:43.425308Z  WARN readdirplus{req=228 ino=1 fh=9 offset=0}: mountpoint_s3::fuse: readdirplus failed: out-of-order readdir, expected=166, actual=0
```

(cc @gimaker)

**Comment by arsh** [comment]
@luiscape is your use case exclusively rewinding (starting from offset 0) and then doing a sequential list? or does it include random seeks on the dir stream?

**Comment by luiscape** [comment]
I noticed this issue when walking the root directory twice in a row (ie calling ls). I haven't noticed this issue on random seeks like you mention.

**Comment by gimaker** [comment]
@arsh Note that `rewinddir(dirp)` is subtly but crucially different from `seekdir(dirp, 0)`. Quoting from [readdir](https://pubs.opengroup.org/onlinepubs/9699919799/functions/readdir.html) specs:

> If a file is removed from or added to the directory after the most recent call to [opendir()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/opendir.html) or [rewinddir()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/rewinddir.html), whether a subsequent call to readdir() returns an entry for that file is unspecified.

(Though as far as I know, from a FUSE perspective there's no way to distinguish a `rewindir(dirp)` and `seekdir(dirp, 0)`)

`rewinddir()` should effectively behave as calling `opendir()` again. Any and files that were added or removed between the `opendir()` and the `rewinddir()` should be reflect in subsequent calls to `readdir()`. `seekdir()` doesn't have the same constraints - `readdir()` may omit files that were added after `opendir()` and after you call `seekdir()` (and may include files that have been deleted).

I am unfamiliar with the mountpoint-s3 code base so I don't know if this is a problem in practice, but I imagine it could be. The C snippet below illustrates the issue:

```
#include <stdio.h>
#include <dirent.h>
#include <assert.h>
#include <string.h>

int main () {
  DIR *dh = opendir("/my-mount");
  if (dh == NULL) {
    printf("failed to open dir\n");
    return -1;
  }

  struct dirent *dirent;
  while ((dirent = readdir(dh)) != NULL) {
    printf("%s\n", dirent->d_name);
  }
  
  // Create new file
  FILE *f = fopen("/my-mount/this-is-new-file", "w");
  if (f == NULL) {
    printf("failed to open file\n");
    return -1;
  }
  fwrite("hello", 5, 1, f);
  fclose(f);

  printf("rewinding\n");
  rewinddir(dh);

  // Newly created file must be returned by readdir() after calling rewinddir()
  int hello_found = 0;
  while ((dirent = readdir(dh)) != NULL) {
    if (strcmp("this-is-new-file", dirent->d_name) == 0) {
      hello_found = 1;
    }
    printf("%s\n", dirent->d_name);
  }

  assert(hello_found == 1);
  
  closedir(dh);
  return 0;
}
```

**Comment by arsh** [comment]
Here is a PR https://github.com/awslabs/mountpoint-s3/pull/825 adding support for `rewinddir`.

**Comment by arsh** [comment]
A fix for this has been merged.

https://github.com/awslabs/mountpoint-s3/pull/825

**Comment by luiscape** [comment]
@arsh awesome! How can we give it a try? Would you have a build link or should we build from main?

**Comment by arsh** [comment]
You will need to build from `main`. Please let us know if you find any issues.

**Comment by luiscape** [comment]
Issue is now fixed. Thanks a lot!
