### ISSUE TITLE
Slurm(srun) unable to start mountpoint 

### ISSUE THREAD

**Issue by lzw06061139** [awslabs/mountpoint-s3#846]
### Mountpoint for Amazon S3 version

mount-s3 1.3.2（build from main branch）

### Describe the running environment

In My LLM-training envrioment,  there are admin nodes and GPU nodes. I use slurm(srun commands) to dispatch task to GPU nodes(CentOS 7.6) in the admin nodes(CentOS 7.6). 

### Mountpoint options

```shell
I use the following slurm command to dispatch mount command, if it runs success, the bucket would mounted on {mountpoint} in the host {hostname} of GPU partition {partition}:

srun -p {partition} -w {hostname} ./bin/mountpoint [-f] {bucket} {mountpoint} --allow-delete --endpoint-url {endpoint} --debug --log-directory ./
```

### What happened?

if I run the mount cmd mentioned above, with -f option( running in foregroud), it runs as will, but if I run it without the -f option the mountpoint process will be terminated without any error logs.  [in addition,  mountpoint can run on the admin nodes normally, the admin nodes and GPU nodes, have the same kernel version, fuse version , gcc version, etc].

the srun's output says mount success as following, 

srun: job 12858977 queued and waiting for resources
srun: job 12858977 has been allocated resources
srun: Job 12858977 scheduled successfully!
Current QUOTA_TYPE is [reserved], which means the job has occupied quota in RESERVED_TOTAL under your partition.
Current PHX_PRIORITY is normal

bucket {bucket} is mounted at {mountpoint}

but actually the mountpoint process has gone , because I run srun with `df -h`, it says "Transport endpoint is not connected" , like this: /usr/bin/df: ‘{mountpoint}’: Transport endpoint is not connected

the logs as following, it looks has no valuble info: 

### Relevant log output

```shell
2024-04-11T07:30:27.164512Z  INFO mountpoint_s3: mountpoint_s3 1.3.2-6e56ed5
2024-04-11T07:30:30.189487Z  WARN mountpoint_s3_client::instance_info: EC2 instance info not retrieved: ImdsQueryFailed(CrtError(Error(1049, "aws-c-io: AWS_IO_SOCKET_NO_ROUTE_TO_HOST, socket connect failure, no route to host.")))
2024-04-11T07:30:30.190878Z  WARN mountpoint_s3: failed to detect network throughput: failed to get instance type: IMDS query failed: Unknown CRT error
2024-04-11T07:30:30.192179Z  INFO mountpoint_s3: target network throughput 10 Gbps
2024-04-11T07:30:30.193416Z DEBUG mountpoint_s3: using default region us-east-1
2024-04-11T07:30:30.194660Z  WARN mountpoint_s3: endpoint specified but region unspecified. using us-east-1 as the signing region.
2024-04-11T07:30:30.255491Z DEBUG list_objects{id=0 bucket="llm-store2" continued=false delimiter="" max_keys="0" prefix=""}: mountpoint_s3_client::s3_crt_client::list_objects: new request
2024-04-11T07:30:30.307148Z DEBUG list_objects{id=0 bucket="llm-store2" continued=false delimiter="" max_keys="0" prefix=""}: mountpoint_s3_client::s3_crt_client: CRT request finished request_type=Default crt_error=None http_status=200 range=None duration=50.231393ms ttfb=Some(47.736214ms) request_id=tx00000000000002268df2e-0066179196-9afab7d-default
2024-04-11T07:30:30.308825Z DEBUG list_objects{id=0 bucket="llm-store2" continued=false delimiter="" max_keys="0" prefix=""}: mountpoint_s3_client::s3_crt_client: meta request finished duration=52.132775ms
2024-04-11T07:30:30.313700Z  INFO fuser::session: Mounting {mountpoint}   
2024-04-11T07:30:30.318645Z  INFO mountpoint_s3: successfully mounted bucket {bucket} at {mountpoint}
2024-04-11T07:30:30.318657Z DEBUG mountpoint_s3::fuse::session: starting fuse worker 0 (thread id 452761)
2024-04-11T07:30:30.319799Z DEBUG mountpoint_s3: success status flag received from child process
2024-04-11T07:30:30.320775Z DEBUG fuser::request: FUSE(  1) ino 0x0000000000000000 INIT kernel ABI 7.22, capabilities 0xf7fb, max readahead 131072    
2024-04-11T07:30:30.320808Z DEBUG mountpoint_s3::fuse::session: starting fuse worker 1 (thread id 452764)
2024-04-11T07:30:30.322817Z DEBUG fuser::request: INIT response: ABI 7.21, flags 0x2021, max readahead 131072, max write 16777216
```

**Comment by lzw06061139** [comment]
By the way:  use the same way to run goofys, it works.

**Comment by passaro** [comment]
Hi. It seems you are able to run Mountpoint when using the `-f` option and even without it, from the logs, it seems Mountpoint starts without issue. Are these logs complete? If not, it would be useful to see the rest.

So far, it looks likely to be a configuration issue with the tool you are using to launch Mountpoint.

**Comment by lzw06061139** [comment]
> Hi. It seems you are able to run Mountpoint when using the `-f` option and even without it, from the logs, it seems Mountpoint starts without issue. Are these logs complete? If not, it would be useful to see the rest.
> 
> So far, it looks likely to be a configuration issue with the tool you are using to launch Mountpoint.

without the -f option mountpoint will terminate silently。 That is the full logs,  and from the log, it really seems without any issues, but the mountpoint process has gone(like been terminated gracefully). Im confused , using the same tool, I  can launch goofys.

**Comment by passaro** [comment]
I am not familiar with slurm, so I cannot really help there. In order to understand whether there is an issue specifically with Mountpoint, I would suggest trying to launch it in background mode (**without** `-f`) directly in a shell on the node:
```
mount-s3 {bucket} {mountpoint} --allow-delete --endpoint-url {endpoint} --debug --log-directory ./
```

Also, would you be able to build or download a recent Mountpoint release (checkout tag `v1.5.0` if building from source)?

**Comment by lzw06061139** [comment]
> I am not familiar with slurm, so I cannot really help there. In order to understand whether there is an issue specifically with Mountpoint, I would suggest trying to launch it in background mode (**without** `-f`) directly in a shell on the node:
> 
> ```
> mount-s3 {bucket} {mountpoint} --allow-delete --endpoint-url {endpoint} --debug --log-directory ./
> ```
> 
> Also, would you be able to build or download a recent Mountpoint release (checkout tag `v1.5.0` if building from source)?

we are only allowed to dispatch task to the GPU nodes with slurm from the admin nodes(logging in to the GPU node is not permitted). 

building from source with tag v1.5.0  code from my ubuntu(16.04) has some errors(build from the main branch as the same):

error[E0308]: mismatched types
  --> mountpoint-s3-crt/src/common/uri.rs:71:18
   |
68 |     pub fn host_port(&self) -> u32 {
   |                                --- expected `u32` because of return type
...
71 |         unsafe { aws_uri_port(self.to_inner_ptr()) }
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u16`
   |
help: you can convert a `u16` to a `u32`
   |
71 |         unsafe { aws_uri_port(self.to_inner_ptr()).into() }
   |                                                   +++++++

error[E0609]: no field `part_size` on type `mountpoint_s3_crt_sys::aws_s3_meta_request_options`
   --> mountpoint-s3-crt/src/s3/client.rs:369:23
    |
369 |         options.inner.part_size = part_size;
    |                       ^^^^^^^^^ unknown field
    |
    = note: available fields are: `type_`, `operation_name`, `signing_config`, `message`, `send_filepath` ... and 12 others

**Comment by lzw06061139** [comment]
I build a mount-s3 from tag v1.4.1 successfully. But the problem still exists。you 

> I am not familiar with slurm, so I cannot really help there. In order to understand whether there is an issue specifically with Mountpoint, I would suggest trying to launch it in background mode (**without** `-f`) directly in a shell on the node:
> 
> ```
> mount-s3 {bucket} {mountpoint} --allow-delete --endpoint-url {endpoint} --debug --log-directory ./
> ```
> 
> Also, would you be able to build or download a recent Mountpoint release (checkout tag `v1.5.0` if building from source)?

I build mount-s3 from tag v1.4.1 successfully.But the problem still exists. I doubt
Are you famillar with goofys? It can be launched with slurm. The following code snippet I copied from goofys demonstrates how it deamonized:
```
		if !flags.Foreground {
			var wg sync.WaitGroup
			waitForSignal(&wg)

			massageArg0()

			ctx := new(daemon.Context)
			child, err = ctx.Reborn()

			if err != nil {
				panic(fmt.Sprintf("unable to daemonize: %v", err))
			}

			InitLoggers(!flags.Foreground && child == nil)

			if child != nil {
				// attempt to wait for child to notify parent
				wg.Wait()
				if waitedForSignal == syscall.SIGUSR1 {
					return
				} else {
					return fuse.EINVAL
				}
			} else {
				// kill our own waiting goroutine
				kill(os.Getpid(), syscall.SIGUSR1)
				wg.Wait()
				defer ctx.Release()
			}

		} else {
			InitLoggers(!flags.Foreground)
		}

		// Mount the file system.
		var mfs *fuse.MountedFileSystem
		var fs *Goofys
		fs, mfs, err = mount(
			context.Background(),
			bucketName,
			flags)

		if err != nil {
			if !flags.Foreground {
				kill(os.Getppid(), syscall.SIGUSR2)
			}
			log.Fatalf("Mounting file system: %v", err)
			// fatal also terminates itself
		} else {
			if !flags.Foreground {
				kill(os.Getppid(), syscall.SIGUSR1)
			}
			log.Println("File system has been successfully mounted.")
			// Let the user unmount with Ctrl-C
			// (SIGINT). But if cache is on, catfs will
			// receive the signal and we would detect that exiting
			registerSIGINTHandler(fs, flags)

			// Wait for the file system to be unmounted.
			err = mfs.Join(context.Background())
			if err != nil {
				err = fmt.Errorf("MountedFileSystem.Join: %v", err)
				return
			}

			log.Println("Successfully exiting.")
		}
```

**Comment by lzw06061139** [comment]
> I notice you are using a FUSE ABI older than Mountpoint supports. Mountpoint requires ABI 7.28. Is it possible to upgrade to a newer operating system?
> 
> > 2024-04-11T07:30:30.320775Z DEBUG fuser::request: FUSE(  1) ino 0x0000000000000000 INIT kernel ABI 7.22, capabilities 0xf7fb, max readahead 131072

My GPU nodes run on CentOS 7.6(kernel 3.10.0-957) and the default installed fuse is 2.9.2，and can't be upgraded now。So I had downgraded the fuse ABI to 7.22。 But，that is not the reason probably because mount-s3 can be launched on the GPU nodes with -f option dispatched by slurm from the Admin nodes，and also can be directly launched with/without -f option on the Admin nodes which has the same kernel and fuse version.

**Comment by arsh** [comment]
When you don't specify `-f`, we `fork` the current process and setup a pipe for interprocess communication to inform the parent the status of the mount (that happens in the child process). From the logs

```
success status flag received from child process
```

it seems everything went as expected.

From the code you provided in goofys, my understanding from https://github.com/sevlyar/go-daemon is that `Reborn` does not actually use `fork` because child process doesn't inherit threads and goroutines in that case.

We don't know anything about slurm but wondering if the child process is getting killed when its parent dies.

**Comment by lzw06061139** [comment]
> When you don't specify `-f`, we `fork` the current process and setup a pipe for interprocess communication to inform the parent the status of the mount (that happens in the child process). From the logs
> 
> ```
> success status flag received from child process
> ```
> 
> it seems everything went as expected.
> 
> From the code you provided in goofys, my understanding from https://github.com/sevlyar/go-daemon is that `Reborn` does not actually use `fork` because child process doesn't inherit threads and goroutines in that case.
> 
> We don't know anything about slurm but wondering if the child process is getting killed when its parent dies.

I had ever tried to add some code lines in the child process just before the code line “session.join()” , which registerd a signal（eg, SIGTERM）handler with crate signal_hook and  defined a flag that waited on until the signal received。It seems the child process get killed immediately after its parent dies.

**Comment by arsh** [comment]
I'm closing this one because this seems to be an issue with your environment. If you feel there is something else we can help with, feel free to reopen this issue.
