### ISSUE TITLE
Support wasabi s3 storage

### ISSUE THREAD

**Issue by tc-hsteffen** [awslabs/mountpoint-s3#850]
### Tell us more about this new feature.

It would be great, if mountpoint-s3 could support wasabi s3 storage, too.
I've spent couple of hours to try it, and managed to get read access. However, writing to the mounted s3 storage fails due to some signature errors, as it seems. Probably it's not so much missing to make it work.

**Comment by passaro** [comment]
Hi, thanks for the feature request. We do not support third-party services. However, we are happy to make changes and/or welcome contributions, provided that they are not specific to another service and, most importantly, do not require separate testing.

For your case in particular, you should probably look at the type of errors you are seeing. If it is a matter of allowing a feature to be disabled, we can definitely consider it. As an example, we are working on making trailing checksums optional in #849.
