### ISSUE TITLE
I think there should be a cool icon for this product

### ISSUE THREAD

**Issue by HaraShun** [awslabs/mountpoint-s3#858]
### Tell us more about this new feature.

Thank you for making such a great product.
The range of architectures that can be drawn on AWS has further expanded.

By the way, there is not a cool icon for this product.
I would like someone to make an icon for this product.

**Comment by jamesbornholt** [comment]
Thanks for the suggestion! We actually do have a cool icon, which you can see on the Mountpoint product page here: https://aws.amazon.com/s3/features/mountpoint/. Hope that helps!
