### ISSUE TITLE
Clarify memory usage limiting in case of `--metadata-ttl` enabled

### ISSUE THREAD

**Issue by mhnap** [awslabs/mountpoint-s3#864]
I have another question about `--metadata-ttl` following #855. Now it's explicitly possible to set `--metadata-ttl` to `indefinite` value. As I understand it's the same as setting the max value manually. But `indefinite` is even mentioned in the documentation, making it an expected usage. So, I have a question is there some logic implemented for memory usage limiting while using `--metadata-ttl=indefinite`? I don't know how much memory can be used by metadata caching for big buckets, but it's quite possible that there could be billions of objects inside. I would be grateful to know whether some memory liming logic exists or it's expected to grow indefinitely.

Thanks for fixing and documenting cache features!

**Comment by monthonk** [comment]
Hey, we don't have any memory limit implemented today so it could also grow indefinitely. We are considering to add some memory limiting mechanism in the future and we will make sure to update our doc for metadata accordingly.

**Comment by arsh** [comment]
I'm closing this issue since anything related to memory limiting mechanism will come with its own update to documentation.
