### ISSUE TITLE
Support executable files

### ISSUE THREAD

**Issue by vincer** [awslabs/mountpoint-s3#866]
### Tell us more about this new feature.

I realize that linux file ownership and permissions aren't supported in the first place on S3. However, it would be very useful if, in particular, the executable bit could be supported by mountpoint so that an executable file can be launched directly from the s3 filesystem, rather than having to cp it out somewhere else to chmod +x it and then run it from there.

I'm thinking `mountpoint-s3` could define some attribute(s) that it can look for in a file to then make it executable.
e.g. if I upload a file with `aws s3 cp --metadata MountpointExecutable=true example.sh s3://bucket/example.sh`, I'd then be able to execute directly from a `mountpoint-s3` filesystem.

**Comment by dannycjones** [comment]
Hey @vincer.

While there's no option to configure the file mode at a per-file granularity, there is currently an option to configure this for the whole file system using `--file-mode <MODE>`. The default is 0644, but could be set to 0755 to allow execution of all files in the file system.

**Comment by vincer** [comment]
Thanks @dannycjones ! 

I somehow missed that option when looking over docs. I think this will probably be sufficient for our immediate use case, so I'll close this for now.
