### ISSUE TITLE
support for s3 mount on ecs variant of bottle rocket

### ISSUE THREAD

**Issue by ssurapan** [awslabs/mountpoint-s3#886]
is the mount point for s3 supported on ecs variant of bottle rocket?

We would like to use it on ECS clusters

**Comment by dannycjones** [comment]
I transferred this issue to the main Mountpoint repository since the CSI driver is only for use in Kubernetes clusters. Let us know if that's incorrect.

**Comment by arsh** [comment]
Closing this issue. Feel free to re-open if needed.
