### ISSUE TITLE
On-premises Direct Connect Integration

### ISSUE THREAD

**Issue by pradoz** [awslabs/mountpoint-s3#902]
### Tell us more about this new feature.

I would like to use (or confirm) that mountpoint-s3 can be used in a scenario that transfers files from an on-prem. through Direct Connect

**Comment by monthonk** [comment]
Hi, I don’t see any obvious blockers for using mountpoint via Direct Connect. If you already have access to AWS services and be able to use tools like awscli to interact with them you should be able to do the same with mountpoint.

**Comment by pradoz** [comment]
Thanks @monthonk - that is the confirmation I was looking for. I will close this for now and open a separate issue with more details if I find that is not the case.
