### ISSUE TITLE
When copying large size data (13-20GB) to an S3 bucket mounted with mount-s3, it takes a long time to respond to requests to S3.

### ISSUE THREAD

**Issue by mura890** [awslabs/mountpoint-s3#939]
### Mountpoint for Amazon S3 version

mount-s3 version：1.7.2

### AWS Region

ap-northeast-1

### Describe the running environment

I am running an S3 bucket in the same account mounted on EC2 (OS: CentOS7.9)

### Mountpoint options

```shell
mount-s3 test-S3-bucket --prefix archives/ /mnt/applications/classtream/archives --uid 1006 --gid 1006 --file-mode 0660 --dir-mode 0770 --allow-delete --allow-other --allow-overwrite --cache /mnt/s3-cache --metadata-ttl 1
```

### What happened?

Copy large files (13GB, 20GB) as shown below to the "archives" area where the S3 bucket is mounted.
cp -p /mnt/13g.mp4 /mnt/applications/classtream/archives/
cp -p /mnt/20g.mp4 /mnt/applications/classtream/archives/

If you execute the following ls command on "archives" during copying, it may take several minutes for the execution results to be displayed.
ls -ltr /mnt/applications/classtream/archives

The execution results of the ls command for an area where S3 is not mounted will be returned immediately.

As a result of the above, there is a section where operations on S3 are no longer accepted, but this occurs only when copying large data, so I have reported it as a bug.

Is there any way to improve it?

**Comment by monthonk** [comment]
Hi @mura890, I tried to reproduce it with the given configurations but did not face the same issue. I think we need more information to investigate.

Could you tell us more about
- How many files are in the `archives` directory?
- Are there other tasks in the background also reading/writing to the mounted path?
- Did you see any differences when using longer `--metadata-ttl`?

Also, it would be really helpful if you can share Mountpoint debug logs when experiencing this issue.

**Comment by mura890** [comment]
Excuse me. As a result of the investigation, it appears that the cause was a violation of the EC2 network performance limit. The phenomenon was improved by changing the instance type.

**Comment by mura890** [comment]
sorry. As a result of the investigation, it appears that the cause was a violation of the EC2 network performance limit. The phenomenon was improved by changing the instance type.

**Comment by mura890** [comment]
sorry. As a result of the investigation, it appears that the cause was a violation of the EC2 network performance limit. The phenomenon was improved by changing the instance type.

We are currently investigating whether the rate of occurrence of this phenomenon can be lowered by adding the option "--maximum-throughput-gbps 1" to limit the transfer amount, but since the limit itself does not apply, we are currently investigating.

**Comment by mura890** [comment]
sorry @monthonk . As a result of the investigation, it appears that the cause was a violation of the EC2 network performance limit. The phenomenon was improved by changing the instance type.

We are currently investigating whether the rate of occurrence of this phenomenon can be lowered by adding the option "--maximum-throughput-gbps 1" to limit the transfer amount, but since the limit itself does not apply, we are currently investigating.

**Comment by monthonk** [comment]
Thanks for sharing the result. If you have a limit on network throughput then lowering `--maximum-troughput-gbps` should really help. Please let me know if you found any issue on Mountpoint.
