### ISSUE TITLE
Cannot successfully mount a S3 Glacier Vault from EC2 instance using instance profile.

### ISSUE THREAD

**Issue by julian-payne** [awslabs/mountpoint-s3#950]
I'm trying to mount a S3 Glacier Vault (Glacier Instant Retrieval) but I've not successfully been able to all day.

As it states in the [configurations](https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#aws-credentials) doc, `aws s3 ls` works (Although I don't know why this is necessary for glacier vaults).

`aws glacier list-vaults` will also list the targeted vault.

The policies for accessing S3 and Glacier are assigned using instance profile.

When I run the mount-s3 command, this is the error I get:
```bash
$ mount-s3 --allow-delete --allow-overwrite --storage-class GLACIER_IR my.archive.bucket /data
Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket my.archive.bucket in region ap-northeast-1
    1: Service error
    2: The bucket does not exist
Error: Failed to create mount process
```

0. is not possible because the instance profile has full access to ALL s3 buckets and glacier without exception (for testing).
1. Service error - I have no idea what this means.
2. Has been confirmed using the `aws glacier list-vaults` command.

So if there is a possibility, it's reason 1. but I have no idea what an "Service error" is.

Has anyone else been able to mount a S3 Glacier successfully?

Many thanks

**Comment by monthonk** [comment]
Hey, [S3 Glacier Vault](https://docs.aws.amazon.com/amazonglacier/latest/dev/introduction.html) is a different service with different APIs from Amazon S3. Mountpoint is a client application that relies on S3's object APIs to support file system operations so it doesn't support S3 Glacier Vault.

What we refer to in the documents are [Amazon S3 Glacier storage classes](https://aws.amazon.com/s3/storage-classes/glacier/). When you test with `aws s3 ls` it means you have a credential with enough permissions to read S3 buckets, including S3 objects in Glacier storage classes (separate from Glacier Vaults).

To use Mountpoint with data in a Glacier Vault, you will need to [transfer the data to an S3 bucket](https://aws.amazon.com/solutions/implementations/data-transfer-from-amazon-s3-glacier-vaults-to-amazon-s3/) first.
