### ISSUE TITLE
Not compatible with Ubuntu 24.04 - libfuse2 -->libfuse3

### ISSUE THREAD

**Issue by mk3rnb8** [awslabs/mountpoint-s3#952]
### Tell us more about this new feature.

Hi Folks,

The package depends on **libfuse2** (fuse2)which is not available for Ubuntu 24.04 anymore.
Ubuntu 24.04 comes with **libfuse3-3** (fuse3)
Would you like to update the code to support libfuse3 for Ubuntu 24.04?

Regards,
Max

apt-get install -y ./mount-s3.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'mount-s3' instead of './mount-s3.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 **mount-s3 : Depends: libfuse2** but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by monthonk** [comment]
Hi, Mountpoint is already compatible with fuse3 but we decided to build and ship it with fuse2 because we want to support older operating systems. We definitely want to continue to support Ubuntu 24.04 and newer operating systems. I will discuss with the team about this.

**Comment by psulightning** [comment]
Wanted to bump this as it would be great to have this for newer OS.

**Comment by monthonk** [comment]
Hey @psulightning, thanks for letting us know! Please also use the thumbs up reaction 👍 on the main post as this is how we measure interest in the feature request.

**Comment by ZhouLihua** [comment]
Hi Guys.  Is this issue resolved.  we met the same issue here.

**Comment by mk3rnb8** [comment]
This request is open since July... How this issue will be fixed? If we cannot use it with the latest Ubuntu version (24), we need to consider to switch from AWS to another provider.

**Comment by monthonk** [comment]
Hi, we are still considering the best way to make it works for newer operating systems. There is nothing to share yet but we will prioritise this work.

**Comment by ZhouLihua** [comment]
> Hi Guys. Is this issue resolved. we met the same issue here.

I solved this problem.  I used image builder to build my solution.  You can refer to it.


> name: mountpoint-s3 install and setup
> description: install mountpoint-s3  and auto mount
> platform: Linux
> schemaVersion: 1.0
> parameters:
>   - user:
>       type: string
>       default: ubuntu
> 
> phases:
>   - name: build
>     steps:
>       - name: DownloadMountpoint-s3Package
>         action: ExecuteBash
>         inputs:
>           commands:
>             - |
>               set -e
>               wget https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.deb
>       - name: InstallMountpoint-s3
>         action: ExecuteBash
>         inputs:
>           commands:
>             - |
>               set -e
>               sudo apt update -y
>               sudo apt install -y libfuse2
>               sudo apt install -y ./mount-s3.deb  # issue for ubuntu 22.04 or higher https://github.com/awslabs/mountpoint-s3/issues/952
>               mount-s3 --version
>       - name: EnableMount-s3AutoMount
>         action: ExecuteBash
>         inputs:
>           commands:
>             - |
>               set -e
>               sudo -u {{ user }} mkdir -p /home/{{ user }}/s3
>               # https://github.com/awslabs/mountpoint-s3/issues/441
>               bucketName="your bucket name"
>               cat <<EOF > mountpoint-s3.service
>               [Unit]
>               Description=Mountpoint for Amazon S3 mount
>               After=cloud-init.target
> 
>               [Service]
>               Type=forking
>               User={{ user }}
>               Group={{ user }}
>               ExecStart=/usr/bin/mount-s3 ${bucketName} /home/{{ user }}/s3 --debug
>               ExecStop=/usr/bin/umount /home/{{ user }}/s3
> 
>               [Install]
>               WantedBy=default.target
>               EOF
>               sudo cp mountpoint-s3.service /etc/systemd/system/mountpoint-s3.service
>               sudo systemctl daemon-reload
>               sudo systemctl enable mountpoint-s3.service
>       - name: CleanUp
>         action: ExecuteBash
>         inputs:
>           commands:
>             - |
>               set -e
>               rm -rf ./mount-s3.deb
>               rm -rf ./mountpoint-s3.service

**Comment by unexge** [comment]
We've updated our [installation instructions for Ubuntu](https://github.com/awslabs/mountpoint-s3/blob/main/doc/INSTALL.md#deb-based-distributions-debian-ubuntu), and we believe this should address the issue. Closing this issue for now, please let us know if you still experience the same issue.
