### ISSUE TITLE
Mountpoint Cache exceeding the ephemeral storage of the pod

### ISSUE THREAD

**Issue by Lyon77** [awslabs/mountpoint-s3#973]
### Mountpoint for Amazon S3 version

mount-s3 1.7.0

### AWS Region

us-east-1

### Describe the running environment

Running in a local Kubernetes cluster on a Linux machine. Credentials were set using env variables.

### Mountpoint options

```shell
mount-s3 test_bucket $FILE_DIR --endpoint-url $ENDPOINT \
          --read-only --force-path-style --auto-unmount --cache=$CACHE_DIR --prefix $PREFIX
```

### What happened?

Bucket was mounted into our pod which had 10 Gi request and limit out of the 100Gi available on the node. We read over 10Gi from the bucket and expected cache eviction to occur, but instead, the pod was evicted by kubernetes for using too much storage. The container was doing nothing besides reading from the bucket. Unfortunately, the CSI driver doesn't fit our needs as we need a dynamic provisioning on endpoints to access. 

### Relevant log output

```shell
Kubernetes output:
Pod ephemeral local storage usage exceeds the total limit of containers 10Gi.
```

**Comment by arsh** [comment]
From some tests I did, I see an extra 1MiB per each 10Mib we cache. That is not surprising as we store checksums and other metadata alongside the file content which is not compressed. In theory, we would not exceed more than 95% of available space but that clearly did not work; need to investigate this further.

In the meantime, can you use the following flag when running Mountpoint `--max-cache-size 9216`? This will limit the total size to a little bit over 9GiB but under 10 GiB.

**Comment by Lyon77** [comment]
Sounds good! By adding that flag, does the max cache size only evaluate that folder or still the entire pod resource? I'm asking because I'm going to have multiple mounted buckets so I want to figure out if the calculation is just per cache folder or will be the sum of all the caches?

**Comment by unexge** [comment]
Hey @Lyon77, the parameter will just affect single cache folder

**Comment by Lyon77** [comment]
Gotcha thanks!

**Comment by unexge** [comment]
I think `--max-cache-size 9216` did the trick. Closing the ticket, feel free to re-open if there is something else.
